"""
Cross-validate EdgeBasedModels.jl against EoN (Python) reference values.
Reference data generated by eon_crossval.py using EoN 1.2.

All scenarios use canonical R₀=2, γ=0.25 on Poisson(5) networks.
"""

using Test
using JSON3
using EdgeBasedModels
using ModelingToolkit
using OrdinaryDiffEq

const ref = JSON3.read(read(joinpath(@__DIR__, "eon_reference.json"), String))

@testset "EoN cross-validation" begin
    @testset "EBCM SIR on Poisson(5)" begin
        @parameters β γ κ
        pgf = poisson_pgf(κ)
        model = build_sir(pgf, β, γ; form = :compact)
        ic = default_initial_conditions(model; seed_fraction = 0.01)
        prob = ODEProblem(model.system,
            merge(ic, Dict(β => 1/6, γ => 0.25, κ => 5.0)), (0.0, 40.0))
        sol = solve(prob, Tsit5(); saveat = 0.2)
        I_curve = compartment(sol, model, :I)
        R_curve = compartment(sol, model, :R)

        @test isapprox(maximum(I_curve), ref.ebcm_poisson5.peak_I; atol=0.005)
        @test isapprox(R_curve[end], ref.ebcm_poisson5.final_size; atol=0.005)
    end

    @testset "Attack rate (final size) on Poisson(5)" begin
        pgf_num = poisson_pgf(5.0)
        prog = DiseaseProgression(
            [DiseaseStage(:I; transmission_rate=1/6), DiseaseStage(:R)],
            [DiseaseTransition(:I, :R, 0.25)]; entry=:I)
        fs_model = StaticConfigurationModel(pgf_num, prog)
        fs = final_size(fs_model)
        @test isapprox(fs.R_infinity, ref.attack_rate_poisson5.attack_rate; atol=0.005)
    end

    @testset "EBCM SIS with reinfection counting on Poisson(5)" begin
        pgf_num = poisson_pgf(5.0)
        @parameters β_r γ_r
        sys = build_sis_reinfection(pgf_num, β_r, γ_r, 1)
        ic = default_initial_conditions(sys; seed_fraction = 0.01)
        sol = solve(ODEProblem(sys.system,
            merge(ic, Dict(β_r => 1/6, γ_r => 0.25)), (0.0, 120.0)),
            Tsit5(); maxiters = 100000)
        totals = reinfection_totals(sys, sol)
        I_end = totals[:I][end]

        # Reinfection counting (L=1) matches EoN compact pairwise to <1%
        @test isapprox(I_end, ref.ebcm_sis_poisson5.endemic_I_compact; rtol=0.01)
    end
end

    @testset "EBCM SEIR on Poisson(5)" begin
        pgf_num = poisson_pgf(5.0)
        @parameters β_seir γ_seir σ_seir
        prog = DiseaseProgression(
            [DiseaseStage(:E; transmission_rate=0),
             DiseaseStage(:I; transmission_rate=β_seir),
             DiseaseStage(:R)],
            [DiseaseTransition(:E, :I, σ_seir),
             DiseaseTransition(:I, :R, γ_seir)]; entry=:E)
        model = StaticConfigurationModel(pgf_num, prog)
        sys = build_edge_system(model; form=:expanded)
        ic = default_initial_conditions(sys; seed_fraction=0.05)
        sol = solve(ODEProblem(sys.system,
            merge(ic, Dict(β_seir=>1/6, γ_seir=>0.25, σ_seir=>0.5)),
            (0.0, 40.0)), Tsit5())
        I_seir = compartment(sol, sys, :I)
        # SEIR peak should be ~0.15 (lower than SIR ~0.23 due to latent period)
        # and match the EoN Gillespie_simple_contagion SSA
        @test 0.10 < maximum(I_seir) < 0.25
        @test maximum(I_seir) < ref.ebcm_poisson5.peak_I  # SEIR peak < SIR peak
    end
