{
  "hash": "0b3c82c4492d16c9880bd143029e70b4",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"E03. Degree heterogeneity: same R₀, different epidemics\"\nsubtitle: \"Five degree distributions with R₀ = 2, lifted and compared with NetworkOutbreaks, with an N-scaling check on the heavy-tailed network\"\n---\n\nR₀ on a configuration network depends on the degree distribution only through the mean excess\ndegree κ_ex = ⟨k(k−1)⟩/⟨k⟩: for SIR with per-contact rate τ and recovery rate γ,\nR₀ = T·κ_ex with T = τ/(τ + γ). The epidemic itself depends on the whole distribution, through\nits probability generating function (PGF) ψ. This page lifts one SIR model onto five networks\nthat share R₀ = 2 and compares each lift with a NetworkOutbreaks ensemble. Four of them also\nshare κ_ex = 5, τ = 1/6 and hence the growth rate r = τ(κ_ex − 1) − γ; the heavy-tailed power\nlaw has κ_ex ≈ 8.66, with τ calibrated to keep R₀ = 2\n[@miller2012edge]. The formula R₀ = T·κ_ex is from Newman (2002), \"Spread of epidemic disease on networks\", Phys. Rev. E 66, 016128.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nusing EdgeBasedModels\nsir = @reaction_network sir begin\n    @parameters τ γ\n    τ, S + I --> 2I\n    γ, I --> R\nend\nmodel = contact_model(sir)\nids = [:sir_reg6, :sir_pois5, :sir_nb4, :sir_bim, :sir_pl]\nscs = Dict(id => scenario(id) for id in ids)\n@assert all(isequivalent(model, scs[id].model) for id in ids)\nmdtable([\"scenario\", \"title\"], [(string(\"`:\", id, \"`\"), scs[id].title) for id in ids])\n```\n\n::: {#shared-cell .cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|     scenario |                                                                  title |\n| ------------:| ----------------------------------------------------------------------:|\n|  `:sir_reg6` |                               SIR on a 6-regular configuration network |\n| `:sir_pois5` |                              SIR on a Poisson(5) configuration network |\n|   `:sir_nb4` |  SIR on a negative binomial (mean 4, variance 8) configuration network |\n|   `:sir_bim` |                         SIR on a bimodal {2, 10} configuration network |\n|    `:sir_pl` | SIR on a truncated power-law (α = 2.5, k = 2…60) configuration network |\n\n:::\n:::\n\n\n\n## Five networks with R₀ = 2\n\nThe five degree laws are 6-regular, Poisson(5), negative binomial with mean 4 and variance 8, a\nbimodal law with degree 2 (probability 5/6) or 10 (probability 1/6), and a power law\np_k ∝ k^{−2.5} on 2 ≤ k ≤ 60. All numbers below are computed by NetworkEpiCore from the\ndescriptors:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nnetrow(id) = (sc = scs[id]; net = sc.network; p = sc.params;\n    (string(\"`:\", id, \"`\"), mean_degree(net), excess_degree(net), pgf(net, 0.0),\n     closure_constant(net), is_poisson_type(net) === nothing ? \"no\" : \"yes\", p[:τ],\n     transmissibility(model, net, p), basic_reproduction_number(model, net, p),\n     early_growth_rate(model, net, p), final_size(model, net, p; initial = sc.initial)))\nmdtable([\"scenario\", \"⟨k⟩\", \"κ_ex\", \"P(k = 0)\", \"K = ψ″(1)/ψ′(1)²\", \"Poisson type\", \"τ\", \"T\", \"R₀\", \"r\", \"R∞\"],\n        [netrow(id) for id in ids])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|     scenario |   ⟨k⟩ |  κ_ex | P(k = 0) | K = ψ″(1)/ψ′(1)² | Poisson type |       τ |      T |  R₀ |      r |     R∞ |\n| ------------:| -----:| -----:| --------:| ----------------:| ------------:| -------:| ------:| ---:| ------:| ------:|\n|  `:sir_reg6` |     6 |     5 |        0 |           0.8333 |          yes |  0.1667 |    0.4 |   2 | 0.4167 | 0.9295 |\n| `:sir_pois5` |     5 |     5 | 0.006738 |                1 |          yes |  0.1667 |    0.4 |   2 | 0.4167 | 0.8002 |\n|   `:sir_nb4` |     4 |     5 |   0.0625 |             1.25 |          yes |  0.1667 |    0.4 |   2 | 0.4167 | 0.6408 |\n|   `:sir_bim` | 3.333 |     5 |        0 |              1.5 |           no |  0.1667 |    0.4 |   2 | 0.4167 | 0.4956 |\n|    `:sir_pl` | 3.985 | 8.663 |        0 |            2.174 |           no | 0.07504 | 0.2309 |   2 |  0.325 | 0.2898 |\n\n:::\n:::\n\n\n\nThe final sizes (fraction ever infected, from the fixed point\nθ∞ = 1 − T + T q ψ′(θ∞)/ψ′(1), R∞ = 1 − q ψ(θ∞), with q = 0.99 the fraction initially susceptible)\nrange from 0.93 on the regular network to 0.29 on the power law, at the same R₀. On a\nheterogeneous network the high-degree nodes are reached first and the epidemic burns through\nthem, while the many low-degree nodes are rarely reached; κ_ex is a property of the nodes reached\nalong edges, not of a typical node.\n\n## Low level and factory, five times\n\nEach network gets the same two constructions: the low-level lift of the Catalyst model, and the\nfactory `build_sir` on the scenario's degree law. The assertion is the same on every row:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction lifts(id)\n    sc   = scs[id]\n    sys  = edge_based(model, sc.network)                       # low level\n    sysF = build_sir(sc.network.degrees, :τ, :γ)               # factory\n    @assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\n    return sys\nend\nsystems = Dict(id => lifts(id) for id in ids)\nmdtable([\"scenario\", \"states of the lifted field\", \"vector fields equal\"],\n        [(string(\"`:\", id, \"`\"), join(string.(\"`\", state_names(symbolic_ode(systems[id])), \"`\"), \", \"),\n          vector_fields_equal(symbolic_ode(systems[id]), symbolic_ode(build_sir(scs[id].network.degrees, :τ, :γ))))\n         for id in ids])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|     scenario |          states of the lifted field | vector fields equal |\n| ------------:| -----------------------------------:| -------------------:|\n|  `:sir_reg6` | `θ`, `φ_I`, `φ_R`, `pop_I`, `pop_R` |                true |\n| `:sir_pois5` | `θ`, `φ_I`, `φ_R`, `pop_I`, `pop_R` |                true |\n|   `:sir_nb4` | `θ`, `φ_I`, `φ_R`, `pop_I`, `pop_R` |                true |\n|   `:sir_bim` | `θ`, `φ_I`, `φ_R`, `pop_I`, `pop_R` |                true |\n|    `:sir_pl` | `θ`, `φ_I`, `φ_R`, `pop_I`, `pop_R` |                true |\n\n:::\n:::\n\n\n\nThe fields differ only in the closure terms ψ′(θ) and ψ″(θ)/ψ′(1). For the bimodal law, for\nexample, ψ(θ) = (5θ² + θ¹⁰)/6:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(systems[:sir_bim])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :edge_based_model_edge_based (5 states)\n  dθ/dt = -φ_I(t)*τ\n  dφ_I/dt = -φ_I(t)*γ - φ_I(t)*τ + 0.30000000000000004q_S*(1.6666666666666667 + 15.0(θ(t)^8))*φ_I(t)*τ\n  dφ_R/dt = φ_I(t)*γ\n  dpop_I/dt = -pop_I(t)*γ + q_S*(1.6666666666666667θ(t) + 1.6666666666666665(θ(t)^9))*φ_I(t)*τ\n  dpop_R/dt = pop_I(t)*γ\n  parameters  τ, q_S, γ\n  domain      θ ∈ (0.05, 1.0)\n```\n:::\n:::\n\n\n\n## The five epidemics\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsols = Dict(id => solve_epidemic(systems[id], scs[id]) for id in ids)\ndets = Dict(id => model_curves(systems[id], sols[id]; t = scs[id].tgrid, label = \"edge-based\") for id in ids)\nplt = plot(; xlabel = \"t (days)\", ylabel = \"prevalence I\", title = \"Edge-based SIR, R₀ = 2 on every network\",\n           legend = :topright)\nfor id in ids\n    plot!(plt, dets[id].t, dets[id][:I]; label = string(\":\", id))\nend\nplt\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-6-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction peakrow(id)\n    d = dets[id]; v = d[:I]; i = argmax(v)\n    (string(\"`:\", id, \"`\"), v[i], d.t[i], d[:cumulative][end])\nend\nmdtable([\"scenario\", \"peak I\", \"t(peak)\", \"R(t_end)\"], [peakrow(id) for id in ids])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|     scenario |  peak I | t(peak) | R(t_end) |\n| ------------:| -------:| -------:| --------:|\n|  `:sir_reg6` |  0.2918 |      11 |   0.9295 |\n| `:sir_pois5` |  0.2323 |   11.25 |   0.8002 |\n|   `:sir_nb4` |  0.1768 |    11.5 |   0.6408 |\n|   `:sir_bim` |   0.134 |   11.25 |   0.4956 |\n|    `:sir_pl` | 0.05812 |    13.5 |   0.2898 |\n\n:::\n:::\n\n\n\nThe four networks with κ_ex = 5 grow at the same rate at first but peak at different heights and\ntimes; the power law grows more slowly (r = 0.325 against 0.417) and ends with the smallest\nepidemic.\n\n## Nominal and realised graphs\n\nNetworkOutbreaks draws a fresh graph for every run, but not by the same sampler for every law.\nA 6-regular law gets a uniform random 6-regular simple graph (`Graphs.random_regular_graph`), and\nthe Poisson law gets the Erdős–Rényi graph G(N, μ/(N − 1)), whose degrees are Binomial(N − 1, μ/(N − 1)).\nNeither sampler has anything to erase. The other three laws use the erased configuration model:\nN degrees are drawn iid from the law, the stubs are paired at random, and self-loops and multi-edges\nare erased. The summaries store the realised degree statistics of every run, so the graphs can be\nchecked against the descriptor:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrefs = Dict(id => scenario_summary(scs[id]) for id in ids)\nusing Statistics\nfunction realrow(id)\n    r = refs[id].realised; net = scs[id].network\n    (string(\"`:\", id, \"`\"), mean_degree(net), mean(r[:mean_degree]), std(r[:mean_degree]),\n     excess_degree(net), mean(r[:excess_degree]), std(r[:excess_degree]),\n     mean(r[:erased_fraction]), mean(r[:clustering]))\nend\nmdtable([\"scenario\", \"⟨k⟩ nominal\", \"⟨k⟩ realised (mean)\", \"sd\", \"κ_ex nominal\", \"κ_ex realised (mean)\", \"sd\",\n         \"erased edge fraction\", \"clustering\"], [realrow(id) for id in ids])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|     scenario | ⟨k⟩ nominal | ⟨k⟩ realised (mean) |      sd | κ_ex nominal | κ_ex realised (mean) |      sd | erased edge fraction | clustering |\n| ------------:| -----------:| -------------------:| -------:| ------------:| --------------------:| -------:| --------------------:| ----------:|\n|  `:sir_reg6` |           6 |                   6 |       0 |            5 |                    5 |       0 |                    0 |   0.000412 |\n| `:sir_pois5` |           5 |               5.004 | 0.03404 |            5 |                5.006 |   0.036 |                    0 |  0.0005045 |\n|   `:sir_nb4` |           4 |               3.999 | 0.03034 |            5 |                4.997 | 0.05004 |            0.0004313 |    0.00062 |\n|   `:sir_bim` |       3.333 |               3.331 | 0.03102 |            5 |                4.993 | 0.05582 |            0.0005057 |   0.000751 |\n|    `:sir_pl` |       3.985 |               3.977 |   0.048 |        8.663 |                8.596 |  0.3295 |             0.001136 |   0.001823 |\n\n:::\n:::\n\n\n\nThe erased fraction is exactly 0 for `:sir_reg6` and `:sir_pois5`, whose samplers produce simple\ngraphs directly. For the three erased-configuration laws at N = 10⁴ it is at most about 0.1% of the edges, and the clustering is of the\norder of 10⁻³, so the graphs are locally tree-like, as the edge-based model assumes. The\npower-law network has the largest run-to-run spread of κ_ex (its hubs dominate ⟨k²⟩).\n\n## Against simulation\n\nEach comparison uses the committed ensemble of its scenario (N = 10⁴, 200 runs, a fresh graph per\nrun, conditioned on a major outbreak):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nMarkdown.MD([reference_note(scs[id], refs[id]) for id in ids])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_reg6`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\nNetworkOutbreaks reference `:sir_pois5`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\nNetworkOutbreaks reference `:sir_nb4`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\nNetworkOutbreaks reference `:sir_bim`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\nNetworkOutbreaks reference `:sir_pl`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell fig-height='5.5' execution_count=1}\n``` {.julia .cell-code}\ncomparisonplot(refs[:sir_reg6], dets[:sir_reg6]; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-10-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell fig-height='5.5' execution_count=1}\n``` {.julia .cell-code}\ncomparisonplot(refs[:sir_pois5], dets[:sir_pois5]; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-11-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell fig-height='5.5' execution_count=1}\n``` {.julia .cell-code}\ncomparisonplot(refs[:sir_nb4], dets[:sir_nb4]; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-12-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell fig-height='5.5' execution_count=1}\n``` {.julia .cell-code}\ncomparisonplot(refs[:sir_bim], dets[:sir_bim]; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-13-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell fig-height='5.5' execution_count=1}\n``` {.julia .cell-code}\ncomparisonplot(refs[:sir_pl], dets[:sir_pl]; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-14-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\nThe metrics, one row per scenario:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncmps = Dict(id => compare(refs[id], dets[id]) for id in ids)\nfunction cmprow(id)\n    rI = cmps[id][\"edge-based\", :I]; rC = cmps[id][\"edge-based\", :cumulative]\n    (string(\"`:\", id, \"`\"), rI.D∞, rI.SE∞, rI.z∞, rI.Δpeak, rI.Δt_peak, rC.ΔR∞,\n     @sprintf(\"[%.4f, %.4f]\", rC.ΔR∞_ci...))\nend\nmdtable([\"scenario\", \"D∞(I)\", \"SE∞(I)\", \"z∞(I)\", \"Δpeak\", \"Δt_peak\", \"ΔR∞\", \"95% CI of ΔR∞\"],\n        [cmprow(id) for id in ids])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|     scenario |    D∞(I) |   SE∞(I) | z∞(I) |     Δpeak | Δt_peak |        ΔR∞ |     95% CI of ΔR∞ |\n| ------------:| --------:| --------:| -----:| ---------:| -------:| ----------:| -----------------:|\n|  `:sir_reg6` | 0.001712 | 0.001166 | 2.769 |  0.001275 |   -0.25 |  0.0002613 | [-0.0003, 0.0008] |\n| `:sir_pois5` | 0.002226 | 0.001135 | 2.587 |  0.001567 |       0 |  0.0001105 | [-0.0009, 0.0011] |\n|   `:sir_nb4` |  0.00115 | 0.001064 | 1.742 | 0.0007551 |       0 |   0.000338 | [-0.0010, 0.0017] |\n|   `:sir_bim` | 0.002319 | 0.001038 | 3.586 |  0.001356 |       0 | -0.0003484 | [-0.0020, 0.0013] |\n|    `:sir_pl` | 0.002645 | 0.000743 | 3.944 |   0.00222 |       0 |   0.001729 | [-0.0005, 0.0040] |\n\n:::\n:::\n\n\n\nOn every network the largest prevalence error is below 0.005 and |ΔR∞| is below 0.005, the\ntolerances of the `:exact_limit` tests. The largest z∞, on the power law, is the finite-N effect\nexamined next.\n\n## N-scaling on the power-law network\n\nA representation that is exact in the large-N limit should approach the ensemble mean as N grows,\ndown to the Monte Carlo floor. `:sir_pl` is also committed at N = 10³ and N = 10⁵, with\nN × runs held at 2·10⁶ so that the standard error of the mean stays roughly constant:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nnids = [:sir_pl_N1000, :sir_pl, :sir_pl_N100000]\nnscs = Dict(id => scenario(id) for id in nids)\nnrefs = Dict(id => scenario_summary(nscs[id]) for id in nids)\n@assert all(canonical_text(nscs[id].model) == canonical_text(scs[:sir_pl].model) for id in nids)\nMarkdown.MD([reference_note(nscs[id], nrefs[id]) for id in nids])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_pl_N1000`: N = 1000, 2000 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 1712 major runs, P(major) = 0.856 (95% CI 0.840–0.871).\n\nNetworkOutbreaks reference `:sir_pl`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\nNetworkOutbreaks reference `:sir_pl_N100000`: N = 100000, 20 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 20 major runs, P(major) = 1.000 (95% CI 0.839–1.000).\n\n:::\n:::\n\n\n\nThe deterministic curve does not depend on N, so the same `dets[:sir_pl]` is compared with all\nthree ensembles:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nfunction nrow(id)\n    ref = nrefs[id]; c = compare(ref, dets[:sir_pl])\n    rI = c[\"edge-based\", :I]; rC = c[\"edge-based\", :cumulative]\n    (ref.N, ref.nsims, mean(ref.realised[:excess_degree]), mean(ref.realised[:erased_fraction]),\n     rI.D∞, rI.SE∞, rI.z∞, rC.ΔR∞)\nend\nnrows = [nrow(id) for id in nids]\nmdtable([\"N\", \"runs\", \"κ_ex realised (mean)\", \"erased edge fraction\", \"D∞(I)\", \"SE∞(I)\", \"z∞(I)\", \"ΔR∞\"], nrows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|      N | runs | κ_ex realised (mean) | erased edge fraction |    D∞(I) |   SE∞(I) | z∞(I) |        ΔR∞ |\n| ------:| ----:| --------------------:| --------------------:| --------:| --------:| -----:| ----------:|\n|   1000 | 2000 |                8.185 |              0.01099 |   0.0118 | 0.000614 | 20.49 |     0.0148 |\n|  10000 |  200 |                8.596 |             0.001136 | 0.002645 | 0.000743 | 3.944 |   0.001729 |\n| 100000 |   20 |                8.645 |            0.0001117 | 0.001396 | 0.000637 | 2.974 | -0.0002687 |\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nNs = [r[1] for r in nrows]; Ds = [r[5] for r in nrows]; SEs = [r[6] for r in nrows]\nplot(Ns, Ds; xscale = :log10, yscale = :log10, marker = :circle, label = \"D∞(I), edge-based vs ensemble mean\",\n     xlabel = \"N\", ylabel = \"max_t |ΔI|\", title = \":sir_pl, N × runs = 2·10⁶\", legend = :topright)\nplot!(Ns, 1.96 .* SEs; marker = :square, linestyle = :dash, label = \"1.96 SE∞ (Monte Carlo floor)\")\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-18-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\nAt N = 10³ the realised graphs lose about 1% of their edges to erasure and their mean excess degree\nfalls below the nominal 8.66, so the ensemble has a smaller epidemic than the limit; D∞ is many\nstandard errors. The error shrinks with N towards the Monte Carlo floor, which is what a\nrepresentation that is exact in the limit does (E06 shows the constant-closure pairwise model on\nthe same network, which plateaus instead).\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [],
    "includes": {}
  }
}