# Golden cases: two-type configuration models through build_edge_system(::MultiTypeConfigurationModel)
# (the 0.1 multitype builder until WP29; since then a deprecation shim forwarding to the multitype lift).
# Owner after Phase 0: WP29 (DESIGN_NetworkEpiCore.md, section G.2). Regenerated by WP29 (NORM_NOTE; the
# 0.1 numbers are kept in v01/ and checked, rescaled, by 00_legacy_multitype.jl). The network is the one of the
# canonical scenario :sir_sbm2 (section E.3): equal type sizes, Poisson partner counts with means
# [6 2; 2 4] (reciprocal for equal sizes), τ = 0.0955 so that T·ρ(M) = 2, γ = 1/4, seed ρ = 0.01
# in every type.

using EdgeBasedModels

const τ = 0.0955
const γ = 1 / 4
const σ = 1 / 5
const ρ = 0.01
const TYPES = [:a, :b]

pgfs() = Dict(:a => multivariate_poisson_pgf(TYPES, Dict(:a => 6.0, :b => 2.0)),
              :b => multivariate_poisson_pgf(TYPES, Dict(:a => 2.0, :b => 4.0)))

sir() = DiseaseProgression([DiseaseStage(:I; transmission_rate = τ), DiseaseStage(:R; transmission_rate = 0)],
                           [DiseaseTransition(:I, :R, γ)]; entry = :I)

seir() = DiseaseProgression([DiseaseStage(:E; transmission_rate = 0), DiseaseStage(:I; transmission_rate = τ),
                             DiseaseStage(:R; transmission_rate = 0)],
                            [DiseaseTransition(:E, :I, σ), DiseaseTransition(:I, :R, γ)]; entry = :E)

const NET = "multivariate_poisson_pgf means a: (a 6, b 2), b: (a 2, b 4)"

const NORM_NOTE = "WP29: node-level columns (S_a, pop_<X>_a) are fractions of all nodes (design J.6), so with the " *
                  "type sizes n_a = n_b = 1/2 inferred from edge reciprocity they are half the 0.1 within-type " *
                  "values; I_a and R_a are gone (pop_<X>_a are the populations), and the edge-level columns are " *
                  "unchanged."

function multitype_case(name, description, prog_fn, T; contact_matrix = Dict{Tuple{Symbol, Symbol}, Any}(),
                        notes = "", setup = Dict{String, Any}())
    return GoldenCase("multitype", name; description = description, issues = ["E26"],
        notes = join_notes(notes, E26_FIXED_NOTE, NORM_NOTE),
        run = () -> edge_system_trajectory(
            build_edge_system(MultiTypeConfigurationModel(types = TYPES, pgfs = pgfs(), progression = prog_fn(),
                                                          contact_matrix = contact_matrix));
            T = T, seed_fraction = ρ,
            setup = merge(Dict{String, Any}("network" => NET, "tau" => τ, "gamma" => γ), setup)))
end

[
    multitype_case("multitype_sir_2type",
        "MultiTypeConfigurationModel SIR, types [:a, :b], Poisson means [6 2; 2 4], τ = 0.0955, γ = 1/4, " *
        "seed ρ = 0.01 per type, t = 0:1:60", sir, 60),
    multitype_case("multitype_sir_2type_cm",
        "as multitype_sir_2type with contact_matrix (a,b) = (b,a) = 1/2, t = 0:1:60", sir, 60;
        contact_matrix = Dict((:a, :b) => 0.5, (:b, :a) => 0.5),
        notes = "contact_matrix is a per-edge transmission-rate multiplier indexed (infector type, infectee type), " *
                "not a mixing matrix (verified issue E32(a)); the equations are correct.",
        setup = Dict("contact_matrix_ab" => 0.5, "contact_matrix_ba" => 0.5)),
    multitype_case("multitype_seir_2type",
        "MultiTypeConfigurationModel SEIR (σ = 1/5) on the same network, seed ρ = 0.01 per type in E, t = 0:1:150",
        seir, 150; setup = Dict("sigma" => σ)),
]
