{
  "hash": "b3ed3e8f819f32e425f1b6603bf0e504",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"E16. Dormant contacts and fleeting heterogeneous contacts (DVD, MFSH)\"\nsubtitle: \"Partnerships that pause and resume, and their fast limit: mean-field social heterogeneity\"\n---\n\n## What this page shows\n\nIn the neighbour-exchange network of [E09](../E09_dynamic_partnerships/index.qmd) a broken edge\nis replaced at once. In the **dormant-contact** (DC) model of Miller and Volz (arXiv:1106.6319,\nPart II §3.2.4) a node has k_m stubs, and each stub is either *active* (half of an edge) or\n*dormant*. An active edge breaks at rate η₂ = η_break and both stubs go dormant. A dormant stub\nreactivates at rate η₁ = η_form by pairing with another reactivating stub. In the limit η₁ → 0,\nwith degrees scaled up, this is the dynamic variable-degree (DVD) model. When η₁ = η₂ → ∞ every\ncontact is fleeting, and the model tends to **mean-field social heterogeneity** (MFSH): each node\nhas an activity k, but meets a new random partner at every contact\n[@miller2012edge; arXiv:1106.6320 §3.1]. EdgeBasedModels lifts any T_EB model to both:\n`DynamicNetwork(base, DormantContacts(η_form, η_break))` and `MFSHNetwork(d)`. This page:\n\n1. builds the dormant-contact SIR of MSV's Figure 5 twice and prints its equations;\n2. compares it with NetworkOutbreaks' `DormantContactProcess` on `:sir_dormant_msv` and\n   `:sir_dormant_dvd`;\n3. shows the fast limit `:sir_dormant_fast` → MFSH with per-contact rate τA;\n4. compares MFSH with NetworkOutbreaks' fleeting-contact SSA on `:sir_mfsh_pois5` and\n   `:sir_mfsh_msv`, including a residual offset at N = 10⁴;\n5. shows MFSH as the η → ∞ limit of neighbour exchange on a Poisson base.\n\n## The shared first cell\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nusing Statistics\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nsir = @reaction_network sir begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ; S converted, I unchanged\n    γ, I --> R             # node-local transition\nend\nmodel = contact_model(sir)          # prints the typing report\nsc    = scenario(:sir_dormant_msv)  # k_m ∈ {2, 8} (½ each), η_form = η_break = 1, τ = γ = 1\n@assert isequivalent(model, sc.model)\nref   = scenario_summary(sc)        # committed NetworkOutbreaks ensemble (DormantContactProcess)\n# --- EBM vignette ---------------------------------------------------------------\nusing EdgeBasedModels\nnet   = DynamicNetwork(EmpiricalDegree(2 => 0.5, 8 => 0.5), DormantContacts(η_form = 1, η_break = 1))\nsys   = edge_based(model, net)                             # low level\nsysF  = build_sir(net, :τ, :γ)                             # factory\n@assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\nlift_contributions(model, net)                             # per-reaction terms and the dormant-contact process\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nLiftContributions :sir on NetworkEpiCore.DynamicNetwork(NetworkEpiCore.ConfigurationNetwork(NetworkEpiCore.EmpiricalDegree([0.0, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.5])), NetworkEpiCore.DormantContacts(1.0, 1.0))  (dormant closure)\n  coordinates  θ, θ_A, θ_D, χ, ξ, φ_I, φ_R, α_I, α_R, π_I, π_R, pop_I, pop_R\n  seed factors q_S (initially susceptible fraction of S)\n  [1] S + I → 2I  (τ)   contact\n        θ'      += -0.5φ_I*τ\n        θ_A'    += -φ_I*τ\n        φ_I'    += -φ_I*τ\n        φ_I'    += 0.1q_S*χ*(1 + 28.0(θ^6))*φ_I*ξ*τ\n        α_I'    += (1/5)*q_S*(θ + 0.5θ_A*(1 + 28.0(θ^6)) + 4.0(θ^7))*φ_I*ξ*τ\n        π_I'    += 0.1q_S*θ_D*(1 + 28.0(θ^6))*φ_I*ξ*τ\n        pop_I'  += 0.5q_S*(θ + 4.0(θ^7))*φ_I*ξ*τ\n  [2] I → R  (γ)   progress\n        φ_I'    += -φ_I*γ\n        φ_R'    += φ_I*γ\n        α_I'    += -α_I*γ\n        α_R'    += α_I*γ\n        π_I'    += -π_I*γ\n        π_R'    += π_I*γ\n        pop_I'  += -pop_I*γ\n        pop_R'  += pop_I*γ\n  [3] dormant contacts  (η_form = 1.0, η_break = 1.0)   process\n        θ_A'    += -θ_A + θ_D\n        θ_D'    += θ_A - θ_D\n        χ'      += -χ + θ_D^2\n        φ_I'    += -φ_I + π_I*θ_D\n        α_I'    += π_I - α_I\n        π_I'    += -π_I + α_I\n        φ_R'    += -φ_R + π_R*θ_D\n        α_R'    += π_R - α_R\n        π_R'    += -π_R + α_R\n```\n:::\n:::\n\n\n\n## The dormant-contact equations\n\nAt stationarity, which the model assumes at t = 0, a stub is active with probability\nA = η₁/(η₁ + η₂) and dormant with probability D = η₂/(η₁ + η₂). The coordinates are:\n\n- θ = Aθ_A + Dθ_D, the probability that a stub has not transmitted to its node, given active\n  (θ_A) or dormant (θ_D);\n- χ, the partnership memory: φ_S = χ q ψ′(θ)/ψ′(1);\n- φ_X, an active stub has not transmitted and is joined to an X node;\n- α_X and π_X, the fractions of active and of dormant stubs that belong to X nodes.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(sys)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :edge_based_model_edge_based (12 states)\n  dθ/dt = -0.5φ_I(t)*τ\n  dθ_A/dt = -θ_A(t) + θ_D(t) - φ_I(t)*τ\n  dθ_D/dt = θ_A(t) - θ_D(t)\n  dχ/dt = -χ(t) + θ_D(t)^2\n  dφ_I/dt = -φ_I(t) + π_I(t)*θ_D(t) - φ_I(t)*γ - φ_I(t)*τ + 0.1q_S*χ(t)*(1 + 28.0(θ(t)^6))*φ_I(t)*τ\n  dφ_R/dt = -φ_R(t) + π_R(t)*θ_D(t) + φ_I(t)*γ\n  dα_I/dt = π_I(t) - α_I(t) - α_I(t)*γ + (1//5)*q_S*(θ(t) + 0.5θ_A(t)*(1 + 28.0(θ(t)^6)) + 4.0(θ(t)^7))*φ_I(t)*τ\n  dα_R/dt = π_R(t) - α_R(t) + α_I(t)*γ\n  dπ_I/dt = -π_I(t) + α_I(t) - π_I(t)*γ + 0.1q_S*θ_D(t)*(1 + 28.0(θ(t)^6))*φ_I(t)*τ\n  dπ_R/dt = -π_R(t) + α_R(t) + π_I(t)*γ\n  dpop_I/dt = -pop_I(t)*γ + 0.5q_S*(θ(t) + 4.0(θ(t)^7))*φ_I(t)*τ\n  dpop_R/dt = pop_I(t)*γ\n  parameters  τ, q_S, γ\n  domain      θ ∈ (0.05, 1.0)\n```\n:::\n:::\n\n\n\nBoth rates enter the field. With symbolic η's the parameters of the lifted system are:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nη₁, η₂ = as_parameter(:η₁), as_parameter(:η₂)          # symbolic parameters\nsyss = edge_based(model, DynamicNetwork(EmpiricalDegree(2 => 0.5, 8 => 0.5), DormantContacts(η₁, η₂)))\nsymbolic_ode(syss).parameters\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n5-element Vector{Any}:\n  η₁\n   τ\n  η₂\n q_S\n   γ\n```\n:::\n:::\n\n\n\nWith η_break = 0 no edge ever breaks, and the model is the static configuration model:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntol = (; reltol = 1e-10, abstol = 1e-12)\ngrid = sc.tgrid\nstatic_dc = edge_based(model, DynamicNetwork(EmpiricalDegree(2 => 0.5, 8 => 0.5), DormantContacts(η_form = 1, η_break = 0)))\nstatic_cm = edge_based(model, ConfigurationNetwork(EmpiricalDegree(2 => 0.5, 8 => 0.5)))\nrun(y, s = sc; label = \"\") = model_curves(y, solve_epidemic(y, s; tol...); t = s.tgrid, label)\nmaximum(abs.(run(static_dc)[:I] .- run(static_cm)[:I]))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n1.3988810110276972e-14\n```\n:::\n:::\n\n\n\nThe EdgeBasedModels test suite checks the field symbolically against a hand transcription of\nMSV's DC equations.\n\n## Against the dormant-contact process\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndet = run(sys; label = \"edge-based (dormant contacts)\")\ncomparisonplot(ref, det; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-6-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sc, ref)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_dormant_msv`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(ref, det)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_dormant_msv  (scenario 10d932b9; conditioned mean of 200 runs)\n  curve                          observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (dormant contacts)  S            0.00239      4.10   0.00206      1.60   0.00073  [-0.00063,  0.00209]   0.00000      0.00     1.000\n  edge-based (dormant contacts)  I            0.00159      3.30   0.00092      3.06   0.00073  [-0.00063,  0.00209]   0.00153      0.10     0.965\n  edge-based (dormant contacts)  R            0.00212      4.70   0.00168      1.45   0.00073  [-0.00063,  0.00209]   0.00073      0.00     1.000\n  edge-based (dormant contacts)  infectious   0.00159      3.30   0.00092      3.06   0.00073  [-0.00063,  0.00209]   0.00153      0.10     0.965\n  edge-based (dormant contacts)  cumulative   0.00239      4.10   0.00206      1.60   0.00073  [-0.00063,  0.00209]   0.00073      0.40     1.000\n```\n:::\n:::\n\n\n\nThe DVD regime, `:sir_dormant_dvd`, has slow reformation (η_form = 0.1, η_break = 1, so A = 1/11)\nand stub numbers {11, 44}. A node has on average k_m A active partners, the degrees {1, 4} of\nthe DVD network in MSV's Figure 5:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsd = scenario(:sir_dormant_dvd)\n@assert isequivalent(model, sd.model)\nrefd = scenario_summary(sd)\nsysd = edge_based(model, sd.network)\ndetd = run(sysd, sd; label = \"edge-based (dormant contacts, DVD regime)\")\ncomparisonplot(refd, detd; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-9-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sd, refd)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_dormant_dvd`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refd, detd; observables = [:S, :I, :R, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_dormant_dvd  (scenario c781d1f2; conditioned mean of 200 runs)\n  curve                                      observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (dormant contacts, DVD regime)  S            0.00134      1.70   0.00211      1.20   0.00048  [-0.00070,  0.00166]   0.00000      0.00     1.000\n  edge-based (dormant contacts, DVD regime)  I            0.00129      3.30   0.00101      2.75   0.00048  [-0.00070,  0.00166]   0.00108      0.00     0.960\n  edge-based (dormant contacts, DVD regime)  R            0.00095      2.60   0.00164      1.07   0.00048  [-0.00070,  0.00166]   0.00048      0.50     1.000\n  edge-based (dormant contacts, DVD regime)  cumulative   0.00134      1.70   0.00211      1.20   0.00048  [-0.00070,  0.00166]   0.00048      1.90     1.000\n```\n:::\n:::\n\n\n\n## The fast limit: dormant contacts → MFSH\n\nIf both rates grow at the same speed, a stub changes partner infinitely often and is active a\nfraction A of the time. The limit is MFSH with per-contact rate τA. For `:sir_dormant_fast`,\nη₁ = η₂ = 10, so A = 1/2 and τA = 1/2. That is the MFSH scenario `:sir_mfsh_msv`:\n\nThe shared recipe `comparisonplot` styles every curve by its representation, so two edge-based\ncurves would come out in the same colour. `style_curves!` gives each curve of a comparison figure its\nown colour and dash, in the order the curves were passed:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    style_curves!(p, styles) -> p\n\nGive the model curves of a `comparisonplot` figure `p` their own line colours and styles.\n`styles` holds one `(linecolor, linestyle)` pair per curve, in the order the curves were passed.\nThe recipe draws the curves last in every panel, so they are the last `length(styles)` series of\neach subplot; the labels of the first panel are checked against `labels`.\n\"\"\"\nfunction style_curves!(p, styles, labels)\n    n = length(styles)\n    first_labels = [s[:label] for s in p.subplots[1].series_list[end-n+1:end]]\n    first_labels == collect(labels) ||\n        error(\"style_curves!: the last series of the first panel are $(first_labels), not $(labels)\")\n    for sp in p.subplots, (k, (lc, ls)) in enumerate(styles)\n        s = sp.series_list[end-n+k]\n        s[:linecolor] = Plots.plot_color(lc)\n        s[:linestyle] = ls\n    end\n    return p\nend\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nMain.Notebook.style_curves!\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsf = scenario(:sir_dormant_fast)\nrefF = scenario_summary(sf)\nsm = scenario(:sir_mfsh_msv)\n@assert sm.network.degrees == sf.network.base.degrees && sm.params[:τ] == sf.params[:τ] / 2\ndetF = run(edge_based(model, sf.network), sf; label = \"edge-based DC, η₁ = η₂ = 10\")\ndetM = run(edge_based(model, sm.network), sm; label = \"MFSH, τA = 1/2\")\np = comparisonplot(refF, detF, detM; observables = [:I, :cumulative])\nstyle_curves!(p, [(:royalblue, :solid), (:crimson, :dash)], [detF.label, detM.label])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-13-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sf, refF)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_dormant_fast`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refF, detF, detM; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_dormant_fast  (scenario 9fabc2c3; conditioned mean of 200 runs)\n  curve                        observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based DC, η₁ = η₂ = 10  I            0.00227      2.40   0.00112      2.86   0.00042  [-0.00043,  0.00127]   0.00121      0.00     0.970\n  edge-based DC, η₁ = η₂ = 10  cumulative   0.00392      2.40   0.00213      2.02   0.00042  [-0.00043,  0.00127]   0.00042      1.00     0.985\n  MFSH, τA = 1/2               I            0.05969      1.90   0.00112     53.46   0.02857  [ 0.02772,  0.02942]   0.03015     -0.30     0.433\n  MFSH, τA = 1/2               cumulative   0.11225      2.20   0.00213     75.02   0.02857  [ 0.02772,  0.02942]   0.02857      1.00     0.010\n```\n:::\n:::\n\n\n\nAt η = 10 the DC model has not yet reached its limit. Its distance from MFSH shrinks as both\nrates grow:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nbasem = EmpiricalDegree(2 => 0.5, 8 => 0.5)\ndc_gap(η) = maximum(abs.(run(edge_based(model, DynamicNetwork(basem, DormantContacts(η_form = η, η_break = η))), sf)[:I] .- detM[:I]))\nηs = [1.0, 10.0, 100.0, 1000.0]\ngaps = dc_gap.(ηs)\nmdtable([\"η₁ = η₂\", \"largest gap in I to MFSH\"], collect(zip(ηs, gaps)))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n| η₁ = η₂ | largest gap in I to MFSH |\n| -------:| ------------------------:|\n|       1 |                    0.154 |\n|      10 |                  0.05805 |\n|     100 |                 0.008001 |\n|    1000 |                0.0008344 |\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ngaps[1:end-1] ./ gaps[2:end]\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n3-element Vector{Float64}:\n 2.6525462714567176\n 7.255451866582568\n 9.589319345628583\n```\n:::\n:::\n\n\n\nThe ratios approach 10 per decade of η, so the distance to MFSH decays like 1/η.\n\n## Mean-field social heterogeneity\n\nMFSH needs only θ (the probability that a stub has never transmitted to its node), π_X (the\nfraction of stubs belonging to X nodes) and the node fractions. Every contact is with a fresh\nrandom stub, so φ_X = θπ_X:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmf = scenario(:sir_mfsh_pois5)       # Poisson(5) activity, τ = 1/12, γ = 1/4\n@assert isequivalent(model, mf.model)\nrefm = scenario_summary(mf)\nsysm = edge_based(model, MFSHNetwork(PoissonDegree(5)))\n@assert vector_fields_equal(symbolic_ode(sysm), symbolic_ode(build_sir(MFSHNetwork(PoissonDegree(5)), :τ, :γ)))\nlift_contributions(model, mf.network)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nLiftContributions :sir on NetworkEpiCore.MFSHNetwork(NetworkEpiCore.PoissonDegree(5.0))  (mfsh closure)\n  coordinates  θ, ξ, π_I, π_R, pop_I, pop_R\n  seed factors q_S (initially susceptible fraction of S)\n  [1] S + I → 2I  (τ)   contact\n        θ'      += -π_I*θ*τ\n        π_I'    += (1/5)*q_S*π_I*θ*(5.0exp(5.0(-1 + θ)) + 25.0θ*exp(5.0(-1 + θ)))*ξ*τ\n        pop_I'  += 5.0q_S*π_I*θ*exp(5.0(-1 + θ))*ξ*τ\n  [2] I → R  (γ)   progress\n        π_I'    += -π_I*γ\n        π_R'    += π_I*γ\n        pop_I'  += -pop_I*γ\n        pop_R'  += pop_I*γ\n```\n:::\n:::\n\n\n\nNetworkOutbreaks simulates it exactly with a *fleeting-contact* SSA (algorithm `:fleeting`): a\nnode of activity k makes contacts at rate τk, each with the owner of a uniformly random stub.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ndetm = run(sysm, mf; label = \"MFSH\")\ncomparisonplot(refm, detm; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-19-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(mf, refm)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_mfsh_pois5`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntabm = compare(refm, detm)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_mfsh_pois5  (scenario 37bd22d3; conditioned mean of 200 runs)\n  curve  observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  MFSH   S            0.00662     17.50   0.00217      3.27   0.00068  [-0.00076,  0.00211]   0.00000      0.00     0.738\n  MFSH   I            0.00251     15.25   0.00083      3.63   0.00068  [-0.00076,  0.00211]   0.00155     -0.25     0.751\n  MFSH   R            0.00569     20.25   0.00189      3.25   0.00068  [-0.00076,  0.00211]   0.00068      3.00     0.708\n  MFSH   infectious   0.00251     15.25   0.00083      3.63   0.00068  [-0.00076,  0.00211]   0.00155     -0.25     0.751\n  MFSH   cumulative   0.00662     17.50   0.00217      3.27   0.00068  [-0.00076,  0.00211]   0.00068      0.00     0.738\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrefm2 = scenario_summary(sm)\nreference_note(sm, refm2)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_mfsh_msv`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntabm2 = compare(refm2, detM)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_mfsh_msv  (scenario d208fe11; conditioned mean of 200 runs)\n  curve           observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  MFSH, τA = 1/2  S            0.00215      2.10   0.00214      1.20   0.00000  [-0.00083,  0.00084]   0.00000      0.00     1.000\n  MFSH, τA = 1/2  I            0.00145      1.80   0.00123      2.03   0.00000  [-0.00083,  0.00084]   0.00082      0.00     0.990\n  MFSH, τA = 1/2  R            0.00141      3.20   0.00147      1.14   0.00000  [-0.00083,  0.00084]   0.00000      0.70     1.000\n  MFSH, τA = 1/2  infectious   0.00145      1.80   0.00123      2.03   0.00000  [-0.00083,  0.00084]   0.00082      0.00     0.990\n  MFSH, τA = 1/2  cumulative   0.00215      2.10   0.00214      1.20   0.00000  [-0.00083,  0.00084]   0.00000      1.10     1.000\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nBoth pass the `:exact_limit` rule (D∞(I) = 0.0025 and 0.0014, ΔR∞ = +0.00068 and +0.00000). On `:sir_mfsh_pois5`, however, z∞ is 3.63 on I and 3.27 on S, while the final size agrees within its confidence interval. This is consistent with a finite-size offset of the fleeting-contact SSA at N = 10⁴, but this page does not show it: N-scaled summaries of the `:sir_mfsh_*` scenarios are not committed, so the N dependence is not demonstrated here. (EdgeBasedModels' test suite, `test/suites/mfsh.jl`, reruns this scenario at N = 4·10⁴ with 100 runs and requires D∞ < 0.005 and z∞ < 4 on every observable. Those bounds are weak evidence for the offset: at N = 10⁴, D∞(I) = 0.0025 and D∞(S) = 0.0066, and z∞(I) = 3.63 is already below 4.)\n\n:::\n:::\n\n\n\nThe threshold and final size of MFSH come from its own next-generation matrix and fixed point:\nR₀ = τ(κ_ex + 1)/γ = τ E[k²]/(E[k]γ):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmdtable([\"scenario\", \"R₀ (formula)\", \"R₀ (EBCM)\", \"R₀ (registry)\", \"final size (fixed point)\", \"R(t_end), ODE\", \"NO mean final size\"],\n        [(string(\"`:\", s.id, \"`\"), s.params[:τ] * (excess_degree(s.network.degrees) + 1) / s.params[:γ],\n          basic_reproduction_number(y; p = s.params), s.expected[:R0],\n          final_size(y; p = s.params, initial = s.initial), c[:cumulative][end], mean(r.final_size[r.major]))\n         for (s, y, c, r) in ((mf, sysm, detm, refm), (sm, edge_based(model, sm.network), detM, refm2))])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|          scenario | R₀ (formula) | R₀ (EBCM) | R₀ (registry) | final size (fixed point) | R(t_end), ODE | NO mean final size |\n| -----------------:| ------------:| ---------:| -------------:| ------------------------:| -------------:| ------------------:|\n| `:sir_mfsh_pois5` |            2 |         2 |             2 |                   0.6687 |        0.6687 |              0.668 |\n|   `:sir_mfsh_msv` |          3.4 |       3.4 |           3.4 |                   0.7846 |        0.7846 |             0.7846 |\n\n:::\n:::\n\n\n\n## MFSH as the η → ∞ limit of neighbour exchange on a Poisson base\n\nOn a Poisson(5) base, neighbour exchange at rate η (E09) tends to MFSH with Poisson(5) activity,\nnot to mass action. The committed scenario at η = 10 is `:sir_ne_pois5_eta10`. Larger η are\nsolved without simulation:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\npbase = ConfigurationNetwork(PoissonDegree(5))\nne_gap(η) = maximum(abs.(run(edge_based(model, DynamicNetwork(pbase, NeighbourExchange(η))), mf)[:I] .- detm[:I]))\nηn = [1.0, 10.0, 100.0, 1000.0]\ngn = ne_gap.(ηn)\nmdtable([\"η\", \"largest gap in I to MFSH\"], collect(zip(ηn, gn)))\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|    η | largest gap in I to MFSH |\n| ----:| ------------------------:|\n|    1 |                  0.03558 |\n|   10 |                 0.005429 |\n|  100 |                0.0005731 |\n| 1000 |                5.763e-05 |\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ngn[1:end-1] ./ gn[2:end]\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n3-element Vector{Float64}:\n 6.55355520015412\n 9.472553597937983\n 9.9446317356224\n```\n:::\n:::\n\n\n\nAgain the gap falls by a factor approaching 10 per decade of η. The committed η = 10 ensemble\nfollows the finite-η model (see the comparison table on [E09](../E09_dynamic_partnerships/index.qmd)).\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsp = scenario(:sir_ne_pois5_eta10)\nrefp = scenario_summary(sp)\ndetp = run(edge_based(model, sp.network), sp; label = \"edge-based DFD, η = 10\")\ndetp1000 = run(edge_based(model, DynamicNetwork(pbase, NeighbourExchange(1000.0))), sp; label = \"edge-based DFD, η = 1000\")\np = plot(refm, :I; median = false, title = \"neighbour exchange → MFSH (Poisson(5) base); SSA: :sir_mfsh_pois5\")\nplot!(p, detp, :I; linecolor = :orange, linestyle = :solid)\nplot!(p, detp1000, :I; linecolor = :royalblue, linestyle = :dash)\nplot!(p, detm, :I; linecolor = :black, linestyle = :dot, linewidth = 3)\nxlims!(p, 0, 60)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-28-output-1.svg){}\n:::\n:::\n\n\n\n## Lean\n\nNone of the dynamic-network statements on this page is formalised.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-commonmark"
    ],
    "filters": [],
    "includes": {}
  }
}