project:
  type: default

engine: julia

freeze: auto

format:
  html:
    toc: true
    code-fold: false
    theme: cosmo
    embed-resources: true
  pdf:
    pdf-engine: xelatex
    mainfont: "STIX Two Text"
    mathfont: "STIX Two Math"
    monofont: "Fira Code"
    toc: true
  gfm:
    toc: true

julia:
  project: "."
