# Golden cases: core (static configuration-model SIR through the legacy builders).
# Owner after Phase 0: WP29 (DESIGN_NetworkEpiCore.md, section G.2). Regenerated by WP29 when the legacy
# builders were deleted (E26_FIXED_NOTE: new names only; the 0.1 numbers are kept in v01/ and checked by
# 00_legacy_core.jl). Canonical anchors (section E.2):
# per-contact rate τ = 1/6, recovery γ = 1/4, seed ρ = 0.01 in the entry state; Poisson(5) and the
# bimodal {2: 5/6, 10: 1/6} network both have excess degree 5, so T = 0.4 and R₀ = 2.
# Rates are numeric (in 0.1 Symbol rates did not reach the builders, verified issue E10).

using EdgeBasedModels
using ModelingToolkit
using Symbolics

const τ = 1 / 6
const γ = 1 / 4
const ρ = 0.01
const P_BIMODAL = [k == 2 ? 5 / 6 : k == 10 ? 1 / 6 : 0.0 for k in 0:10]

const E31_NOTE = "The expanded S observable is (1-ρ)ψ(θ), as verified issue E31 confirms is correct (the 0.1 " *
                 "HEAD had S = ψ(θ), so S(0) = 1)."

function sir_case(name, network_label, pgf_fn, form; notes = "")
    return GoldenCase("core", name;
        description = "build_sir($network_label, τ = 1/6, γ = 1/4; form = :$form), seed ρ = 0.01 in I, t = 0:1:60",
        issues = ["E26"], notes = join_notes(notes, E26_FIXED_NOTE),
        run = () -> edge_system_trajectory(build_sir(pgf_fn(), τ, γ; form = form);
            T = 60, seed_fraction = ρ,
            setup = Dict("builder" => "build_sir", "network" => network_label, "form" => string(form),
                         "tau" => τ, "gamma" => γ)))
end

[
    sir_case("sir_pois5_compact", "poisson_pgf(5.0)", () -> poisson_pgf(5.0), :compact),
    sir_case("sir_pois5_expanded", "poisson_pgf(5.0)", () -> poisson_pgf(5.0), :expanded; notes = E31_NOTE),
    sir_case("sir_bim_compact", "polynomial_pgf(bimodal {2: 5/6, 10: 1/6})", () -> polynomial_pgf(P_BIMODAL), :compact),
    sir_case("sir_bim_expanded", "polynomial_pgf(bimodal {2: 5/6, 10: 1/6})", () -> polynomial_pgf(P_BIMODAL), :expanded;
             notes = E31_NOTE),
    GoldenCase("core", "sir_pois5_symkappa_expanded";
        description = "build_sir(poisson_pgf(κ), τ = 1/6, γ = 1/4; form = :expanded) with a symbolic mean degree κ = 5 " *
                      "supplied at solve time; must equal sir_pois5_expanded",
        issues = ["E26"], notes = join_notes(E31_NOTE, E26_FIXED_NOTE),
        run = function ()
            κ = only(@parameters κ)
            sys = build_sir(poisson_pgf(κ), τ, γ; form = :expanded)
            return edge_system_trajectory(sys; T = 60, seed_fraction = ρ, op_extra = Dict(κ => 5.0),
                setup = Dict("builder" => "build_sir", "network" => "poisson_pgf(κ), κ = 5.0", "form" => "expanded",
                             "tau" => τ, "gamma" => γ, "kappa" => 5.0))
        end),
    GoldenCase("core", "pgf_scalars"; kind = :scalars,
        description = "mean_degree and PGF derivatives at 1 of the legacy DegreePGF constructors",
        run = function ()
            s = Dict{String, Any}()
            for (label, pgf) in (("pois5", poisson_pgf(5.0)), ("bim", polynomial_pgf(P_BIMODAL)),
                                 ("poly_023_05", polynomial_pgf([0.2, 0.3, 0.5])),
                                 ("reg6", polynomial_pgf([0, 0, 0, 0, 0, 0, 1.0])))
                s["$(label)_mean_degree"] = mean_degree(pgf)
                for order in 1:3
                    d = pgf_derivative(pgf, order)
                    s["$(label)_psi_d$(order)_at_1"] = Symbolics.substitute(d, Dict(pgf.variable => 1.0))
                end
            end
            return scalar_result(Dict("networks" => ["poisson_pgf(5.0)", "polynomial_pgf(bimodal {2: 5/6, 10: 1/6})",
                                                     "polynomial_pgf([0.2, 0.3, 0.5])", "polynomial_pgf(6-regular)"]), s)
        end),
]
