{
  "hash": "09656458697e65e40ab60690c49c49af",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"E15. Degree correlations\"\nsubtitle: \"The joint-degree (2K) edge-based model, its sampler, and how assortative mixing changes R₀ and the epidemic\"\n---\n\n## What this page shows\n\nIn a configuration network the degrees at the two ends of an edge are independent. Real contact\nnetworks are often **assortative**, with high-degree people linked to each other, or\n**disassortative**. A `DegreeCorrelatedNetwork` gives the degree classes k, their node fractions\np_k and a symmetric edge-end matrix e_kl, the fraction of edge ends joining degree k to degree l.\nA degree-k node's neighbours then have degree l with probability Q(l | k) = e_kl / Σ_m e_km.\nEdgeBasedModels lifts any T_EB model onto it with one θ_k per degree class\n[@wang2018edge; @miller2013incorporating]. This page:\n\n1. builds `degree_correlated(p; r)` from the bimodal degree law of `:sir_bim` with Newman's\n   r-mixing [@newman2002assortative], and lifts SIR twice;\n2. checks NetworkOutbreaks' 2K sampler: its realised joint-degree matrix and assortativity against\n   the targets;\n3. compares the EBCM with simulation at r = −0.5, 0 and 0.5 (`:sir_dc_bim_*`);\n4. computes R₀ from the next-generation matrix (l − 1)Q(l | k)T, and shows that assortativity\n   raises it.\n\n## The shared first cell\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nusing Statistics, LinearAlgebra\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nsir = @reaction_network sir begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ; S converted, I unchanged\n    γ, I --> R             # node-local transition\nend\nmodel = contact_model(sir)          # prints the typing report\nsc    = scenario(:sir_dc_bim_r05)   # bimodal {2: 5/6, 10: 1/6}, Newman r = 0.5, τ = 1/6, γ = 1/4\n@assert isequivalent(model, sc.model)\nref   = scenario_summary(sc)        # committed NetworkOutbreaks ensemble on 2K graphs\n# --- EBM vignette ---------------------------------------------------------------\nusing EdgeBasedModels\nbimodal = EmpiricalDegree(2 => 5 / 6, 10 => 1 / 6)\nnet   = degree_correlated(bimodal; r = 0.5)\nsys   = edge_based(model, net)                             # low level\nsysF  = build_sir(net, :τ, :γ)                             # factory\n@assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\nlift_contributions(model, net)                             # per-reaction, per-degree-class terms\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nLiftContributions :sir on NetworkEpiCore.DegreeCorrelatedNetwork([2, 10], [0.8333333333333334, 0.16666666666666666], [0.3750000000000001 0.12500000000000003; 0.12500000000000003 0.375])  (degree_correlated closure)\n  coordinates  θ_k2, θ_k10, ξ, φ_I_k2, φ_I_k10, φ_R_k2, φ_R_k10, pop_I, pop_R\n  seed factors q_S (initially susceptible fraction of S)\n  [1] S + I → 2I  (τ)   contact\n        θ_k2'     += -φ_I_k2*τ\n        φ_I_k2'   += -φ_I_k2*τ\n        θ_k10'    += -φ_I_k10*τ\n        φ_I_k10'  += -φ_I_k10*τ\n        φ_I_k2'   += q_S*(0.75φ_I_k2 + 2.25(θ_k10^8)*φ_I_k10)*ξ*τ\n        φ_I_k10'  += q_S*(0.25000000000000006φ_I_k2 + 6.75(θ_k10^8)*φ_I_k10)*ξ*τ\n        pop_I'    += q_S*(1.6666666666666667θ_k2*φ_I_k2 + 1.6666666666666665(θ_k10^9)*φ_I_k10)*ξ*τ\n  [2] I → R  (γ)   progress\n        φ_I_k2'   += -φ_I_k2*γ\n        φ_R_k2'   += φ_I_k2*γ\n        φ_I_k10'  += -φ_I_k10*γ\n        φ_R_k10'  += φ_I_k10*γ\n        pop_I'    += -pop_I*γ\n        pop_R'    += pop_I*γ\n```\n:::\n:::\n\n\n\n## The descriptor\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(; degrees = net.degrees, p = net.probabilities, e = net.edge_ends,\n   Q = net.edge_ends ./ sum(net.edge_ends; dims = 2), assortativity = degree_assortativity(net),\n   mean_degree = mean_degree(net), excess_degree = excess_degree(net))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(degrees = [2, 10], p = [0.8333333333333334, 0.16666666666666666], e = [0.3750000000000001 0.12500000000000003; 0.12500000000000003 0.375], Q = [0.75 0.25; 0.25000000000000006 0.75], assortativity = 0.5, mean_degree = 3.333333333333333, excess_degree = 5.000000000000001)\n```\n:::\n:::\n\n\n\nNewman's r-mixing takes e = (1 − r) q qᵀ + r diag(q), where q_k = k p_k/⟨k⟩ is the edge-end\ndistribution. It keeps the degree law and the edge-end marginals, so the mean degree (10/3) and\nthe excess degree (5) are those of `:sir_bim` for every r:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nqk = net.degrees .* net.probabilities ./ mean_degree(net)       # edge-end distribution q_k\nmaximum(abs.(net.edge_ends .- ((1 - 0.5) .* qk * qk' .+ 0.5 .* Diagonal(qk))))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n0.0\n```\n:::\n:::\n\n\n\n## The lifted equations\n\nThe partner at the end of an edge into a degree-k node has degree l with probability Q(l | k),\nand it is still susceptible with probability q θ_l^{l−1}. So\n\nS = q Σ_k p_k θ_k^k,   φ_{S,k} = q Σ_l Q(l | k) θ_l^{l−1},\n\nand a contact adds τ q Σ_l Q(l | k)(l − 1) θ_l^{l−2} φ_{I,l} to φ_{I,k}:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(sys)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :edge_based_model_edge_based (8 states)\n  dθ_k2/dt = -φ_I_k2(t)*τ\n  dθ_k10/dt = -φ_I_k10(t)*τ\n  dφ_I_k2/dt = -φ_I_k2(t)*γ - φ_I_k2(t)*τ + q_S*(0.75φ_I_k2(t) + 2.25(θ_k10(t)^8)*φ_I_k10(t))*τ\n  dφ_I_k10/dt = -φ_I_k10(t)*γ - φ_I_k10(t)*τ + q_S*(0.25000000000000006φ_I_k2(t) + 6.75(θ_k10(t)^8)*φ_I_k10(t))*τ\n  dφ_R_k2/dt = φ_I_k2(t)*γ\n  dφ_R_k10/dt = φ_I_k10(t)*γ\n  dpop_I/dt = -pop_I(t)*γ + q_S*(1.6666666666666667θ_k2(t)*φ_I_k2(t) + 1.6666666666666665(θ_k10(t)^9)*φ_I_k10(t))*τ\n  dpop_R/dt = pop_I(t)*γ\n  parameters  τ, γ, q_S\n  domain      θ_k2 ∈ (0.05, 1.0)\n  domain      θ_k10 ∈ (0.05, 1.0)\n```\n:::\n:::\n\n\n\nWith r = 0, Q(l | k) = q_l for every k. Then all θ_k are equal and the lift reduces to the\nconfiguration lift of ψ(x) = Σ_k p_k x^k, which is `:sir_bim`:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ns0 = scenario(:sir_dc_bim_r0)\ny0 = edge_based(model, s0.network)\nybim = edge_based(model, ConfigurationNetwork(bimodal))\ntol = (; reltol = 1e-11, abstol = 1e-13)\nc0 = model_curves(y0, solve_epidemic(y0, s0; tol...); t = s0.tgrid, label = \"r = 0\")\ncb = model_curves(ybim, solve_epidemic(ybim, s0; tol...); t = s0.tgrid, label = \"configuration\")\n(; max_I = maximum(abs.(c0[:I] .- cb[:I])), max_cumulative = maximum(abs.(c0[:cumulative] .- cb[:cumulative])))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(max_I = 1.1657341758564144e-15, max_cumulative = 2.55351295663786e-15)\n```\n:::\n:::\n\n\n\n## The 2K sampler\n\nNetworkOutbreaks samples a `DegreeCorrelatedNetwork` by assigning the class sizes N p_k (largest\nremainders), rounding N⟨k⟩e to an integer symmetric joint-degree matrix, and matching stubs\nclass pair by class pair. Self-loops and repeated edges are then erased. One draw at N = 10⁴ for\neach r:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrows = map((:sir_dc_bim_rn05, :sir_dc_bim_r0, :sir_dc_bim_r05)) do id\n    s = scenario(id)\n    g, info = sample_graph(s.network, 10_000; rng = NetworkOutbreaks.stable_rng(s.sim.base_seed + 1))\n    (string(\"`:\", id, \"`\"), degree_assortativity(s.network), info.assortativity,\n     maximum(abs.(info.realised_joint_degree .- s.network.edge_ends)), info.mean_degree,\n     info.excess_degree, info.erased_fraction)\nend\nmdtable([\"scenario\", \"target r\", \"realised r\", \"max abs. error in e\", \"mean degree\", \"excess degree\", \"erased fraction\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|           scenario | target r | realised r | max abs. error in e | mean degree | excess degree | erased fraction |\n| ------------------:| --------:| ----------:| -------------------:| -----------:| -------------:| ---------------:|\n| `:sir_dc_bim_rn05` |     -0.5 |    -0.5003 |            0.000165 |       3.332 |         4.997 |         0.00036 |\n|   `:sir_dc_bim_r0` |        0 |  -0.001051 |           0.0003152 |       3.331 |         4.994 |       0.0006599 |\n|  `:sir_dc_bim_r05` |      0.5 |     0.4987 |           0.0004729 |       3.331 |          4.99 |       0.0008999 |\n\n:::\n:::\n\n\n\nThe committed ensembles draw a fresh 2K graph for every run, and record the realised statistics:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrows = map((:sir_dc_bim_rn05, :sir_dc_bim_r0, :sir_dc_bim_r05)) do id\n    r = scenario_summary(scenario(id))\n    (string(\"`:\", id, \"`\"), mean(r.realised[:mean_degree]), std(r.realised[:mean_degree]),\n     mean(r.realised[:excess_degree]), std(r.realised[:excess_degree]))\nend\nmdtable([\"scenario\", \"mean degree (runs)\", \"sd\", \"excess degree (runs)\", \"sd\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|           scenario | mean degree (runs) |        sd | excess degree (runs) |       sd |\n| ------------------:| ------------------:| ---------:| --------------------:| --------:|\n| `:sir_dc_bim_rn05` |              3.333 | 0.0004319 |                4.998 | 0.001286 |\n|   `:sir_dc_bim_r0` |              3.332 | 0.0006265 |                4.995 | 0.002258 |\n|  `:sir_dc_bim_r05` |              3.331 | 0.0007871 |                4.989 |  0.00292 |\n\n:::\n:::\n\n\n\n## EBCM against simulation for r = −0.5, 0, 0.5\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nids = [:sir_dc_bim_rn05, :sir_dc_bim_r0, :sir_dc_bim_r05]\nres = map(ids) do id\n    s = scenario(id)\n    @assert isequivalent(model, s.model)\n    r = scenario_summary(s)\n    y = edge_based(model, s.network)\n    c = model_curves(y, solve_epidemic(y, s); t = s.tgrid, label = \"EBCM r = $(degree_assortativity(s.network))\")\n    (; sc = s, ref = r, sys = y, curves = c)\nend\ncomparisonplot(res[3].ref, res[3].curves; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-9-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(res[3].sc, res[3].ref)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_dc_bim_r05`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(res[3].ref, res[3].curves)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_dc_bim_r05  (scenario 6efbd6f8; conditioned mean of 200 runs)\n  curve         observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  EBCM r = 0.5  S            0.00460      6.75   0.00144      3.36   0.00005  [-0.00087,  0.00098]   0.00000      0.00     0.859\n  EBCM r = 0.5  I            0.00268      5.50   0.00090      3.76   0.00005  [-0.00087,  0.00098]   0.00082      0.00     0.768\n  EBCM r = 0.5  R            0.00291      8.75   0.00094      3.12   0.00005  [-0.00087,  0.00098]   0.00005      0.25     0.776\n  EBCM r = 0.5  infectious   0.00268      5.50   0.00090      3.76   0.00005  [-0.00087,  0.00098]   0.00082      0.00     0.768\n  EBCM r = 0.5  cumulative   0.00460      6.75   0.00144      3.36   0.00005  [-0.00087,  0.00098]   0.00005      7.00     0.859\n```\n:::\n:::\n\n\n\nAll three values of r, prevalence only (grey: SSA q2.5–q97.5 and mean):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nplts = map(res) do w\n    p = plot(w.ref, :I; median = false, title = \"r = $(round(degree_assortativity(w.sc.network); digits = 2))\",\n             legend = false, xlabel = \"t\", ylabel = \"I\")\n    plot!(p, w.curves, :I; label = \"edge-based (2K)\")\n    xlims!(p, 0, 40)\nend\n# one legend for the three panels, in its own strip under them\nleg = plot(res[1].ref, :I; median = false, framestyle = :none, legend = :top, legend_columns = 3,\n           xlims = (-2, -1), ylims = (-2, -1), xlabel = \"\", ylabel = \"\")\nplot!(leg, res[1].curves, :I; label = \"edge-based (2K)\")\nplot(plts..., leg; layout = @layout([a b c; d{0.12h}]), size = (1000, 400),\n     left_margin = 5Plots.mm, bottom_margin = 4Plots.mm)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-12-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n``` {.julia .cell-code}\nfor w in res\n    display(reference_note(w.sc, w.ref))\nend\n```\nNetworkOutbreaks reference `:sir_dc_bim_rn05`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\nNetworkOutbreaks reference `:sir_dc_bim_r0`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\nNetworkOutbreaks reference `:sir_dc_bim_r05`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrows = map(res) do w\n    row = compare(w.ref, w.curves; observables = [:I])[w.curves.label, :I]\n    (degree_assortativity(w.sc.network), w.sc.expected[:final_size], w.curves[:cumulative][end],\n     mean(w.ref.final_size[w.ref.major]), maximum(w.curves[:I]), maximum(w.ref.cond[:I].mean),\n     row.D∞, row.z∞, row.ΔR∞)\nend\nmdtable([\"r\", \"R∞ (NEC registry)\", \"R∞ (EBCM, end of run)\", \"R∞ (NO)\", \"peak I (EBCM)\",\n         \"peak I (NO mean)\", \"D∞(I)\", \"z∞\", \"ΔR∞\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|    r | R∞ (NEC registry) | R∞ (EBCM, end of run) | R∞ (NO) | peak I (EBCM) | peak I (NO mean) |    D∞(I) |    z∞ |       ΔR∞ |\n| ----:| -----------------:| ---------------------:| -------:| -------------:| ----------------:| --------:| -----:| ---------:|\n| -0.5 |            0.5286 |                0.5285 |  0.5269 |       0.09855 |          0.09756 | 0.001052 | 1.705 |  0.001586 |\n|    0 |            0.4956 |                0.4956 |  0.4952 |         0.134 |           0.1327 | 0.002477 | 3.379 | 0.0003819 |\n|  0.5 |            0.3869 |                0.3869 |  0.3869 |        0.1302 |           0.1294 | 0.002678 | 3.762 | 5.479e-05 |\n\n:::\n:::\n\n\n\nWith assortative mixing the final size is *smaller* (0.387 against 0.496 at r = 0), although R₀\nand the early growth rate are larger (next section). The degree-10 nodes infect each other\nearly, while the degree-2 nodes, linked mostly to each other, are reached less. The peak\nprevalence changes little between r = 0 and r = 0.5. With disassortative mixing the epidemic\ngrows more slowly, peaks lower and ends larger.\n\n## R₀ under degree correlation\n\nLinearising the φ_{I,k} equations at the disease-free state gives the next-generation matrix\nK_kl = T (l − 1) Q(l | k), with T = τ/(τ + γ). An infected degree-l partner passes infection along\nits l − 1 other edges. R₀ is its spectral radius. Only the degree classes that have edges enter,\nso degree-0 classes must be dropped (the *support-restricted* matrix).\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nT = sc.params[:τ] / (sc.params[:τ] + sc.params[:γ])\nfunction r0_hand(n)\n    ks = n.degrees\n    keep = findall(>(0), ks)\n    Q = n.edge_ends[keep, keep] ./ sum(n.edge_ends[keep, keep]; dims = 2)\n    K = [T * (ks[keep][l] - 1) * Q[k, l] for k in eachindex(keep), l in eachindex(keep)]\n    maximum(abs.(eigvals(K)))\nend\nrows = map(res) do w\n    (degree_assortativity(w.sc.network), r0_hand(w.sc.network), w.sc.expected[:R0],\n     basic_reproduction_number(w.sys; p = w.sc.params), w.sc.expected[:r])\nend\nmdtable([\"r\", \"R₀ (by hand)\", \"R₀ (NetworkEpiCore)\", \"R₀ (EBCM)\", \"early growth rate\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|    r | R₀ (by hand) | R₀ (NetworkEpiCore) | R₀ (EBCM) | early growth rate |\n| ----:| ------------:| -------------------:| ---------:| -----------------:|\n| -0.5 |        1.485 |               1.485 |     1.485 |             0.202 |\n|    0 |            2 |                   2 |         2 |            0.4167 |\n|  0.5 |        2.737 |               2.737 |     2.737 |            0.7237 |\n\n:::\n:::\n\n\n\nAt r = 0 the matrix has rank one and R₀ = T κ_ex = 0.4 × 5 = 2. Assortative mixing concentrates\ntransmission among the degree-10 nodes, whose excess degree is 9, and raises R₀. A sweep over r:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrs = -0.8:0.1:0.8\nR0s = [r0_hand(degree_correlated(bimodal; r)) for r in rs]\nplot(rs, R0s; xlabel = \"Newman assortativity r\", ylabel = \"R₀\", label = \"R₀ = ρ(T (l − 1) Q(l | k))\",\n     marker = :circle, legend = :topleft, title = \"bimodal {2, 10}, T = 0.4\")\nhline!([2.0]; linecolor = :gray, linestyle = :dash, label = \"r = 0 (configuration)\")\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-16-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(; monotone_increasing = issorted(R0s), R0_at_minus08 = first(R0s), R0_at_08 = last(R0s))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(monotone_increasing = true, R0_at_minus08 = 1.2917875251164943, R0_at_08 = 3.2449913494550757)\n```\n:::\n:::\n\n\n\n## Lean\n\nNone of the degree-correlation statements on this page is formalised.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [],
    "includes": {}
  }
}