# Golden cases: SEIR and multistage progressions on Poisson(5) through the factories and
# build_edge_system (the 0.1 expanded builder until WP29, the per-reaction assembler since).
# Owner after Phase 0: WP29 (DESIGN_NetworkEpiCore.md, section G.2). Regenerated by WP29 (E26_FIXED_NOTE:
# new names only; the 0.1 numbers are kept in v01/ and checked by 00_legacy_seir_multistage.jl). Anchors (section E.2):
# τ = 1/6, γ = 1/4, σ = 1/5, seed ρ = 0.01 in the unique entry state (E for SEIR, I₁ for Erlang).
# Erlang stages follow the documented convention of expand_erlang_stages: the exit transition is
# given the sub-stage rate n·(stage rate), which is the true Erlang(n, n·rate) sojourn. That
# makes these goldens invariant under the E09 fix (total_rate sets the timing, exit rates only
# the branching), whereas the legacy tests that pass the stage-level rate change behaviour.

using EdgeBasedModels

const τ = 1 / 6
const γ = 1 / 4
const σ = 1 / 5
const ρ = 0.01

const SEED_NOTE = "Seeds the entry stage E (EBM default; verified issue E28 documents the convention)."

function static_case(name, description, prog_fn, T; notes = "", setup = Dict{String, Any}())
    return GoldenCase("seir_multistage", name; description = description, issues = ["E26"],
        notes = join_notes(notes, E26_FIXED_NOTE),
        run = () -> edge_system_trajectory(
            build_edge_system(StaticConfigurationModel(poisson_pgf(5.0), prog_fn()); form = :expanded);
            T = T, seed_fraction = ρ,
            setup = merge(Dict{String, Any}("network" => "poisson_pgf(5.0)", "form" => "expanded",
                                            "tau" => τ, "gamma" => γ), setup)))
end

[
    GoldenCase("seir_multistage", "seir_pois5";
        description = "build_seir(poisson_pgf(5.0), σ = 1/5, τ = 1/6, γ = 1/4), seed ρ = 0.01 in E, t = 0:1:150",
        issues = ["E26"], notes = join_notes(SEED_NOTE, E26_FIXED_NOTE),
        run = () -> edge_system_trajectory(build_seir(poisson_pgf(5.0), σ, τ, γ);
            T = 150, seed_fraction = ρ,
            setup = Dict("builder" => "build_seir", "network" => "poisson_pgf(5.0)", "form" => "expanded",
                         "tau" => τ, "gamma" => γ, "sigma" => σ))),
    static_case("sir_erlang3_pois5",
        "expand_erlang_stages([ErlangStage(:I, 3, γ; transmission_rate = τ), DiseaseStage(:R)], [I → R at 3γ]); " *
        "Erlang(3, 3γ) infectious period with mean 1/γ; seed ρ = 0.01 in I_1, t = 0:1:60",
        () -> expand_erlang_stages([ErlangStage(:I, 3, γ; transmission_rate = τ), DiseaseStage(:R)],
                                   [DiseaseTransition(:I, :R, 3γ)]; entry = :I),
        60; setup = Dict("n_I" => 3, "exit_rate" => 3γ)),
    static_case("seir_erlang_pois5",
        "expand_erlang_stages with E ~ Erlang(2, 2σ) (exit 2σ) and I ~ Erlang(3, 3γ) (exit 3γ), τ = 1/6; " *
        "seed ρ = 0.01 in E_1, t = 0:1:150",
        () -> expand_erlang_stages(
            [ErlangStage(:E, 2, σ; transmission_rate = 0), ErlangStage(:I, 3, γ; transmission_rate = τ), DiseaseStage(:R)],
            [DiseaseTransition(:E, :I, 2σ), DiseaseTransition(:I, :R, 3γ)]; entry = :E),
        150; notes = SEED_NOTE, setup = Dict("sigma" => σ, "n_E" => 2, "n_I" => 3)),
    static_case("seir_twostage_pois5",
        "DiseaseProgression E(0) → I1(τ) → I2(τ/2) → R with rates σ, 2γ, 2γ (heterogeneous infectivity, " *
        "mean infectious period 1/γ); seed ρ = 0.01 in E, t = 0:1:150",
        () -> DiseaseProgression(
            [DiseaseStage(:E; transmission_rate = 0), DiseaseStage(:I1; transmission_rate = τ),
             DiseaseStage(:I2; transmission_rate = τ / 2), DiseaseStage(:R; transmission_rate = 0)],
            [DiseaseTransition(:E, :I1, σ), DiseaseTransition(:I1, :I2, 2γ), DiseaseTransition(:I2, :R, 2γ)];
            entry = :E),
        150; notes = SEED_NOTE, setup = Dict("sigma" => σ, "tau_I2" => τ / 2)),
]
