# Golden cases: the 0.1 categorical layer (tensor, stratify) and its 0.2 replacements.
# Owner after Phase 0: WP29 (DESIGN_NetworkEpiCore.md, section G.2). Regenerated by WP29, when
# src/categorical.jl was deleted (the 0.1 numbers are kept in v01/ and checked by 00_legacy_categorical.jl):
#
# - tensor_sir_pois5_pois3: `tensor` is a deprecation shim forwarding to NetworkEpiCore's disjoint_union on
#   the block-diagonal MultitypeNetwork (law H8); node-level columns are fractions of all nodes, half the 0.1
#   within-component values, and the edge-level columns are unchanged.
# - stratify_sir_pois5, stratify_sir_bim: `stratify(::OpenEBCM, strata, mixing)` is an error (verified
#   issue E24); these cases are the replacement, `edge_based(stratify(sir_model(), st), net)` on the typed
#   network of the 0.1 mixing matrix M (equal sizes): Poisson blocks κM (the 0.1 construction, which was
#   right for a Poisson base) and the pull-back SplitDegrees(bimodal, M[i, :]) (which 0.1 got wrong: E24).
# - mass_action_scalars (to_mass_action, verified issue E08) is retired: to_mass_action is an error, and its
#   replacement mass_action(sys; form) is tested in test/suites/reverse.jl.

using EdgeBasedModels

const τ = 1 / 6
const γ = 1 / 4
const ρ = 0.01
const P_BIMODAL = [k == 2 ? 5 / 6 : k == 10 ? 1 / 6 : 0.0 for k in 0:10]
const MIXING = [0.7 0.3; 0.3 0.7]
const ST = strata([:young, :old])

const TENSOR_NOTE = "WP29: tensor forwards to disjoint_union(:a => ..., :b => ...) on the block-diagonal " *
                    "MultitypeNetwork with sizes 1/2 (law H8). Node-level columns (S_a, pop_<X>_a) are " *
                    "fractions of all nodes, half the 0.1 within-component values; I_a and R_a are gone; the " *
                    "edge-level columns are unchanged."

# The typed network of a 0.1 mixing matrix for a degree law d: node type i splits its degree over the
# types with the probabilities M[i, :] (for Poisson d this is the 0.1 multivariate Poisson with means κM).
split_network(d) = MultitypeNetwork(ST.names, ST.sizes,
    MultivariateDegree[SplitDegrees(d, [b => MIXING[i, j] for (j, b) in enumerate(ST.names)])
                       for i in eachindex(ST.names)])

# 0.1 seeded ρ in every stratum: a fraction ρ/2 of all nodes in each (design J.6)
const SEEDS = SeedFraction(:I_young => ρ / 2, :I_old => ρ / 2)

function stratify_case(name, label, d; issues, notes)
    return GoldenCase("categorical", name;
        description = "edge_based(stratify(sir_model(τ = 1/6, γ = 1/4), strata([:young, :old])), MultitypeNetwork " *
                      "with SplitDegrees($label, M[i, :])), M = [0.7 0.3; 0.3 0.7], sizes 1/2, seed ρ = 0.01 per " *
                      "stratum, t = 0:1:60 (the replacement of the 0.1 stratify(open_sir(...), strata, M))",
        issues = issues, notes = notes,
        run = () -> edge_system_trajectory(
            edge_based(stratify(sir_model(; τ, γ), ST), split_network(d));
            T = 60, seed_fraction = ρ, initial = SEEDS,
            setup = Dict("network" => label, "tau" => τ, "gamma" => γ, "strata" => ["young", "old"],
                         "mixing_row1" => MIXING[1, :], "mixing_row2" => MIXING[2, :])))
end

[
    GoldenCase("categorical", "tensor_sir_pois5_pois3";
        description = "build_edge_system(tensor(open_sir(poisson_pgf(5.0), 1/6, 1/4; name = :a), " *
                      "open_sir(poisson_pgf(3.0), 0.3, 1/4; name = :b))), seed ρ = 0.01 in each, t = 0:1:60",
        issues = ["E26"], notes = join_notes(E26_FIXED_NOTE, TENSOR_NOTE),
        run = () -> edge_system_trajectory(
            build_edge_system(tensor(open_sir(poisson_pgf(5.0), τ, γ; name = :a),
                                     open_sir(poisson_pgf(3.0), 0.3, γ; name = :b)));
            T = 60, seed_fraction = ρ,
            setup = Dict("networks" => ["poisson_pgf(5.0)", "poisson_pgf(3.0)"], "tau" => [τ, 0.3],
                         "gamma" => [γ, γ]))),
    stratify_case("stratify_sir_pois5", "PoissonDegree(5.0)", PoissonDegree(5.0); issues = ["E24"],
        notes = "For a Poisson base the pull-back ψ(Σⱼ Mᵢⱼ xⱼ) is the multivariate Poisson with means κM[i, :] that " *
                "the 0.1 stratify built, so the numbers are the 0.1 ones (rescaled: node-level columns are " *
                "fractions of all nodes)."),
    stratify_case("stratify_sir_bim", "bimodal {2: 5/6, 10: 1/6}", EmpiricalDegree(P_BIMODAL); issues = ["E24"],
        notes = "E24 fixed (WP29): 0.1 kept only the base mean degree (10/3) and replaced the bimodal law by a " *
                "multivariate Poisson; the pull-back keeps every node's degree. With a symmetric M, equal sizes " *
                "and equal seeds the strata stay identical, so the totals equal the unstratified bimodal model " *
                "core/sir_bim_expanded (checked in 00_legacy_categorical.jl)."),
]
