{
  "hash": "263df46c6c4b9487b74d63c931bdb1f9",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"E09. Dynamic partnerships\"\nsubtitle: \"Neighbour exchange at rate η: the dynamic fixed-degree (DFD) edge-based model, the η-sweep, and its limits\"\n---\n\n## What this page shows\n\nIn a static configuration network an infected node can only reach the partners it had at the\nstart. If partnerships are **exchanged** while degrees stay fixed, an infected node keeps\nmeeting new partners, and the epidemic gets closer to the well-mixed one. Miller, Slim and Volz\n[@miller2012edge] give an exact edge-based model for this *dynamic fixed-degree* (DFD) network.\nTwo edges (u, v) and (x, y) break at rate η and reform as (u, y) and (x, v), so every node keeps\nits degree. EdgeBasedModels lifts any T_EB reaction network to it with\n`edge_based(model, DynamicNetwork(base, NeighbourExchange(η)))`.\n\nThe page:\n\n1. builds the model twice, from a Catalyst reaction network and with the factory, and prints\n   the lifted equations;\n2. compares the EBCM with NetworkOutbreaks' exact simulation of the swap process at η = 0.1, 1\n   and 10 on a 6-regular base;\n3. shows that as η grows the model tends to mass action with β = 6τ, which is the\n   well-mixed scenario `:sir_wm5`;\n4. explains why on a Poisson base it tends to a *different* limit, the mean-field social\n   heterogeneity (MFSH) model of [E16](../E16_dormant_fleeting/index.qmd).\n\n## The shared first cell\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nusing Statistics\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nsir = @reaction_network sir begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ; S converted, I unchanged\n    γ, I --> R             # node-local transition\nend\nmodel = contact_model(sir)          # prints the typing report\nsc    = scenario(:sir_ne_reg6_eta1) # 6-regular base, neighbour exchange η = 1, τ = 1/12, γ = 1/4\n@assert isequivalent(model, sc.model)\nref   = scenario_summary(sc)        # committed NetworkOutbreaks ensemble of the swap process\n# --- EBM vignette ---------------------------------------------------------------\nusing EdgeBasedModels\nsys   = edge_based(model, sc.network)                      # low level\nsysF  = build_sir(sc.network, :τ, :γ)                      # factory\n@assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\nlift_contributions(model, sc.network)                      # per-reaction terms, plus the exchange process\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nLiftContributions :sir on NetworkEpiCore.DynamicNetwork(NetworkEpiCore.ConfigurationNetwork(NetworkEpiCore.RegularDegree(6)), NetworkEpiCore.NeighbourExchange(1.0))  (dynamic closure)\n  coordinates  θ, ξ, χ, φ_I, φ_R, π_I, π_R, pop_I, pop_R\n  seed factors q_S (initially susceptible fraction of S)\n  [1] S + I → 2I  (τ)   contact\n        θ'      += -φ_I*τ\n        φ_I'    += -φ_I*τ\n        φ_I'    += 5*q_S*χ*(θ^4)*φ_I*ξ*τ\n        π_I'    += 6*q_S*(θ^5)*φ_I*ξ*τ\n        pop_I'  += 6q_S*(θ^5)*φ_I*ξ*τ\n  [2] I → R  (γ)   progress\n        φ_I'    += -φ_I*γ\n        φ_R'    += φ_I*γ\n        π_I'    += -π_I*γ\n        π_R'    += π_I*γ\n        pop_I'  += -pop_I*γ\n        pop_R'  += pop_I*γ\n  [3] neighbour exchange  (1.0)   process\n        χ'      += -χ + θ^2\n        φ_I'    += -φ_I + π_I*θ\n        φ_R'    += -φ_R + π_R*θ\n```\n:::\n:::\n\n\n\nThe typing report of the model, and the scenario:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmodel\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nContactModel :sir  (source: Catalyst.ReactionSystem; method: stoichiometry; rates: PerContact)\n  species       S (Sus)   I   R\n  contacts      [1] S + I → I + I    τ    contact     infector I, entry I\n  transitions   [2] I → R            γ    progress\n  typing        T_EB  ⇒  edge_based ✓  s_anchored ✓  pairwise ✓  individual ✓  pair ✓  stochastic ✓  mass_action ✓\n  assumptions   Sus inferred as recipients \\ contact products = {S}\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nprintln(sc.title)\nprintln(\"network: \", sc.network)\nprintln(\"parameters: \", sort(collect(sc.params); by = first))\nprintln(\"seeding: \", sc.initial, \";  t ∈ \", sc.tspan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSIR on a 6-regular network with neighbour exchange η = 1.0\nnetwork: DynamicNetwork{NeighbourExchange{Float64}}(ConfigurationNetwork{RegularDegree}(RegularDegree(6)), NeighbourExchange{Float64}(1.0))\nparameters: [:γ => 0.25, :τ => 0.08333333333333333]\nseeding: SeedFraction([:I => 0.01], nothing);  t ∈ (0.0, 100.0)\n```\n:::\n:::\n\n\n\nThe per-contact rate is τ = 1/12 here, half the canonical 1/6. With τ = 1/6 the η → ∞ limit\nwould be mass action with β = 6τ = 1, R₀ = 4. At τ = 1/12 the limit is β = 1/2, γ = 1/4, which\nis exactly `:sir_wm5` (R₀ = 2).\n\n## The lifted equations\n\nThe table above lists the terms each reaction contributes; the neighbour exchange appears as a\nthird row of type `process`. The coordinates are:\n\n- θ, the probability that a random partner has not yet transmitted along its current edge;\n- φ_X, the probability that the partner is in state X and has not transmitted;\n- χ, which carries the part of φ_S that edges re-formed since t = 0 contribute (the base-network\n  factor is ψ′(θ)/ψ′(1));\n- π_X, the probability that the node at the end of a random *stub* is in state X. A stub keeps\n  its node while its partner changes, so after an exchange the new partner is in state X with\n  probability π_X.\n\nThe expanded vector field, symbolically, is:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(sys)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :edge_based_model_edge_based (8 states)\n  dθ/dt = -φ_I(t)*τ\n  dχ/dt = -χ(t) + θ(t)^2\n  dφ_I/dt = -φ_I(t) + π_I(t)*θ(t) - φ_I(t)*γ - φ_I(t)*τ + (5//1)*q_S*χ(t)*(θ(t)^4)*φ_I(t)*τ\n  dφ_R/dt = -φ_R(t) + π_R(t)*θ(t) + φ_I(t)*γ\n  dπ_I/dt = -π_I(t)*γ + (6//1)*q_S*(θ(t)^5)*φ_I(t)*τ\n  dπ_R/dt = π_I(t)*γ\n  dpop_I/dt = -pop_I(t)*γ + 6q_S*(θ(t)^5)*φ_I(t)*τ\n  dpop_R/dt = pop_I(t)*γ\n  parameters  τ, γ, q_S\n  domain      θ ∈ (0.05, 1.0)\n```\n:::\n:::\n\n\n\nAt η = 1 the exchange terms are −χ + θ², −φ_X + θπ_X. A broken edge is replaced by a new edge\nwhose partner is a random stub, which has not transmitted with probability θ. This is MSV's DFD\nsystem; EdgeBasedModels' test suite checks it symbolically against a hand transcription of their\nequations (Part I §3.2). The node observables are S = q_S ψ(θ), pop_I and pop_R, where the\nseed factor q_S is the initially susceptible fraction.\n\n## Against the swap process at η = 1\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsol = solve_epidemic(sys, sc)                              # p, initial, tspan, saveat from the scenario\ndet = model_curves(sys, sol; t = sc.tgrid, label = \"edge-based (DFD)\")\ncomparisonplot(ref, det; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-6-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sc, ref)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_ne_reg6_eta1`: N = 5000, 100 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 100 major runs, P(major) = 1.000 (95% CI 0.963–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntab = compare(ref, det)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_ne_reg6_eta1  (scenario c77453d7; conditioned mean of 100 runs)\n  curve             observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (DFD)  S            0.00591     18.50   0.00452      1.75  -0.00024  [-0.00302,  0.00254]   0.00000      0.00     1.000\n  edge-based (DFD)  I            0.00193     13.25   0.00149      1.64  -0.00024  [-0.00302,  0.00254]  -0.00039      0.00     1.000\n  edge-based (DFD)  R            0.00537     19.00   0.00405      1.84  -0.00024  [-0.00302,  0.00254]  -0.00024      1.50     1.000\n  edge-based (DFD)  infectious   0.00193     13.25   0.00149      1.64  -0.00024  [-0.00302,  0.00254]  -0.00039      0.00     1.000\n  edge-based (DFD)  cumulative   0.00591     18.50   0.00452      1.75  -0.00024  [-0.00302,  0.00254]  -0.00024      1.75     1.000\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nAt η = 1 the largest gap between the EBCM prevalence and the ensemble mean is D∞(I) = 0.0019 (z∞ = 1.64), and the final-size difference is ΔR∞ = -0.0002 (95% CI -0.0030 to +0.0025).\n\n:::\n:::\n\n\n\nThe shared recipe `comparisonplot` styles every curve by its representation, so two edge-based\ncurves would come out in the same colour. `style_curves!` gives each curve of a comparison figure its\nown colour and dash, in the order the curves were passed:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    style_curves!(p, styles) -> p\n\nGive the model curves of a `comparisonplot` figure `p` their own line colours and styles.\n`styles` holds one `(linecolor, linestyle)` pair per curve, in the order the curves were passed.\nThe recipe draws the curves last in every panel, so they are the last `length(styles)` series of\neach subplot; the labels of the first panel are checked against `labels`.\n\"\"\"\nfunction style_curves!(p, styles, labels)\n    n = length(styles)\n    first_labels = [s[:label] for s in p.subplots[1].series_list[end-n+1:end]]\n    first_labels == collect(labels) ||\n        error(\"style_curves!: the last series of the first panel are $(first_labels), not $(labels)\")\n    for sp in p.subplots, (k, (lc, ls)) in enumerate(styles)\n        s = sp.series_list[end-n+k]\n        s[:linecolor] = Plots.plot_color(lc)\n        s[:linestyle] = ls\n    end\n    return p\nend\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nMain.Notebook.style_curves!\n```\n:::\n:::\n\n\n\n## The η-sweep\n\nThe three committed scenarios differ only in η. For each we lift the same `model`, solve, and\ncompare with its own NetworkOutbreaks ensemble.\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nids = [:sir_ne_reg6_eta01, :sir_ne_reg6_eta1, :sir_ne_reg6_eta10]\nsweep = map(ids) do id\n    s = scenario(id)\n    @assert isequivalent(model, s.model)\n    r = scenario_summary(s)\n    y = edge_based(model, s.network)\n    c = model_curves(y, solve_epidemic(y, s); t = s.tgrid, label = \"EBCM η = $(s.network.process.η)\")\n    (; id, sc = s, ref = r, sys = y, curves = c, table = compare(r, c))\nend\nplts = map(sweep) do w\n    η = w.sc.network.process.η\n    p = plot(w.ref, :I; median = false, title = \"η = $(η)\", legend = false, xlabel = \"t\", ylabel = \"I\")\n    plot!(p, w.curves, :I; label = \"edge-based (DFD)\")\n    xlims!(p, 0, 60)\nend\n# one legend for the three panels, in its own strip under them\nleg = plot(sweep[1].ref, :I; median = false, framestyle = :none, legend = :top, legend_columns = 3,\n           xlims = (-2, -1), ylims = (-2, -1), xlabel = \"\", ylabel = \"\")\nplot!(leg, sweep[1].curves, :I; label = \"edge-based (DFD)\")\nplot(plts..., leg; layout = @layout([a b c; d{0.12h}]), size = (1000, 400),\n     left_margin = 5Plots.mm, bottom_margin = 4Plots.mm)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-11-output-1.svg){}\n:::\n:::\n\n\n\n``` {.julia .cell-code}\nfor w in sweep\n    display(reference_note(w.sc, w.ref))\nend\n```\nNetworkOutbreaks reference `:sir_ne_reg6_eta01`: N = 5000, 100 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 100 major runs, P(major) = 1.000 (95% CI 0.963–1.000).\n\nNetworkOutbreaks reference `:sir_ne_reg6_eta1`: N = 5000, 100 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 100 major runs, P(major) = 1.000 (95% CI 0.963–1.000).\n\nNetworkOutbreaks reference `:sir_ne_reg6_eta10`: N = 5000, 100 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 100 major runs, P(major) = 1.000 (95% CI 0.963–1.000).\n\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrows = map(sweep) do w\n    η = w.sc.network.process.η\n    row = w.table[w.curves.label, :I]\n    R∞_eb = w.curves[:cumulative][end]\n    R∞_no = mean(w.ref.final_size[w.ref.major])\n    (η, w.sc.expected[:R0], R∞_eb, R∞_no, row.D∞, row.z∞, row.ΔR∞)\nend\nmdtable([\"η\", \"R₀\", \"R∞ (EBCM)\", \"R∞ (NO, major runs)\", \"D∞(I)\", \"z∞(I)\", \"ΔR∞\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|   η |    R₀ | R∞ (EBCM) | R∞ (NO, major runs) |    D∞(I) | z∞(I) |        ΔR∞ |\n| ---:| -----:| ---------:| -------------------:| --------:| -----:| ----------:|\n| 0.1 | 1.423 |    0.5835 |              0.5815 | 0.002161 | 2.616 |   0.002023 |\n|   1 | 1.812 |    0.7469 |              0.7472 | 0.001927 | 1.636 | -0.0002362 |\n|  10 | 1.976 |    0.7939 |              0.7947 | 0.002067 |  3.82 | -0.0007482 |\n\n:::\n:::\n\n\n\nThe `:exact_limit` criteria of the validation protocol are D∞(I) < 0.005 and |ΔR∞| < 0.005\n(see [E14](../E14_validation/index.qmd)). Whether every row meets them, and the largest z∞:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(; all_pass = all(r -> r[5] < 0.005 && abs(r[7]) < 0.005, rows), max_z = maximum(r -> r[6], rows))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(all_pass = true, max_z = 3.819781544761488)\n```\n:::\n:::\n\n\n\nz∞ divides by the pointwise standard error of a mean of only 100 runs (N = 5000), so a z∞ of\nabout 3 to 4 at one of 401 grid points corresponds to an absolute gap of about 0.002.\n\n### R₀ as a function of η\n\nMSV give the reproduction number of the DFD model in closed form\n[@miller2012edge; arXiv:1106.6320 §3.2.1]:\nR₀ = τ/(τ + η + γ) · (η/γ + (η + γ)/γ · κ_ex), with κ_ex = ⟨k(k−1)⟩/⟨k⟩ the excess degree\n(5 on the 6-regular base). The registry's R₀ is computed by NetworkEpiCore's next-generation\nengine, and EdgeBasedModels' is the next-generation matrix of the lifted ODE:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmsv_R0(τ, γ, η, κ) = τ / (τ + η + γ) * (η / γ + (η + γ) / γ * κ)\nκ = excess_degree(sc.network.base)\nrows = map(sweep) do w\n    η = w.sc.network.process.η\n    (η, msv_R0(w.sc.params[:τ], w.sc.params[:γ], η, κ), w.sc.expected[:R0],\n     basic_reproduction_number(w.sys; p = w.sc.params))\nend\nmdtable([\"η\", \"R₀ (MSV closed form)\", \"R₀ (NetworkEpiCore NGM)\", \"R₀ (EBCM)\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|   η | R₀ (MSV closed form) | R₀ (NetworkEpiCore NGM) | R₀ (EBCM) |\n| ---:| --------------------:| -----------------------:| ---------:|\n| 0.1 |                1.423 |                   1.423 |     1.423 |\n|   1 |                1.812 |                   1.812 |     1.812 |\n|  10 |                1.976 |                   1.976 |     1.976 |\n\n:::\n:::\n\n\n\n## The η → ∞ limit on a regular base: mass action, `:sir_wm5`\n\nOn a k-regular base every node has the same degree, so once partners are reshuffled infinitely\nfast a node's k contacts are a random sample of the population. The limit is mass action with\nβ = kτ (MSV Part II; the Λ3 road in DESIGN §D.5). Here that is β = 6/12 = 1/2 with γ = 1/4,\nwhich is exactly the scenario `:sir_wm5` (a `WellMixed(5)` network with τ = 1/10, i.e. β = 5τ).\n\nWe solve the DFD model for larger η (no simulation needed) and measure its distance from the\nedge-based model on `WellMixed(5)`, which by the unit law is mass action:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nwm = scenario(:sir_wm5)\n@assert isequivalent(model, wm.model)\nrefwm = scenario_summary(wm)\nsyswm = edge_based(model, wm.network)\ndetwm = model_curves(syswm, solve_epidemic(syswm, wm; reltol = 1e-10, abstol = 1e-12); t = wm.tgrid,\n                     label = \"mass action (β = 1/2)\")\n\nbase = ConfigurationNetwork(RegularDegree(6))\n# the settings of `sc` (τ = 1/12, γ = 1/4, 1% seeds in I) on the grid of :sir_wm5\nfunction ne_curves(net, label)\n    y = edge_based(model, net)\n    s = solve_epidemic(y; p = sc.params, initial = sc.initial, tspan = wm.tspan, saveat = wm.tgrid,\n                       reltol = 1e-10, abstol = 1e-12)\n    model_curves(y, s; t = wm.tgrid, label)\nend\ndfd_curves(η) = ne_curves(DynamicNetwork(base, NeighbourExchange(η)), \"EBCM η = $(η)\")\nstatic = ne_curves(base, \"static (η = 0)\")\nηs = [0.1, 1.0, 10.0, 100.0, 1000.0]\nlimit = [dfd_curves(η) for η in ηs]\ngap(c) = maximum(abs.(c[:I] .- detwm[:I]))\nrows = vcat([(0.0, static[:cumulative][end], gap(static))],\n            [(η, c[:cumulative][end], gap(c)) for (η, c) in zip(ηs, limit)])\npush!(rows, (Inf, detwm[:cumulative][end], 0.0))\nmdtable([\"η\", \"R(60)\", \"largest gap in I to mass action\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|    η |  R(60) | largest gap in I to mass action |\n| ----:| ------:| -------------------------------:|\n|    0 | 0.5092 |                          0.1153 |\n|  0.1 | 0.5763 |                          0.0997 |\n|    1 | 0.7454 |                         0.04457 |\n|   10 | 0.7936 |                        0.006803 |\n|  100 | 0.7991 |                       0.0007184 |\n| 1000 | 0.7996 |                       7.224e-05 |\n|  Inf | 0.7997 |                               0 |\n\n:::\n:::\n\n\n\nThe factor by which the gap shrinks per tenfold increase of η (for η = 0.1 → 1, 1 → 10, 10 → 100\nand 100 → 1000):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n[gap(limit[i]) / gap(limit[i + 1]) for i in 1:length(ηs) - 1]\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n4-element Vector{Float64}:\n 2.237106152193629\n 6.550796156945916\n 9.470086349120622\n 9.945000138719085\n```\n:::\n:::\n\n\n\nThe factors approach 10 for large η, so the distance to mass action decays like 1/η. (The\nsolves use tolerances 10⁻¹⁰/10⁻¹² so that the solver error stays below the η = 1000 gap.)\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np = plot(refwm, :I; median = false, legend = :topright,\n         title = \"neighbour exchange → mass action (6-regular base); SSA: :sir_wm5\")\nplot!(p, static, :I; linecolor = :gray, linestyle = :dash)\nfor (c, col) in zip(limit[1:4], [:orange, :forestgreen, :teal, :royalblue])\n    plot!(p, c, :I; linecolor = col, linestyle = :solid, linewidth = 1.5)\nend\nplot!(p, detwm, :I; linecolor = :purple, linestyle = :dot, linewidth = 3)\nxlims!(p, 0, 60)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-18-output-1.svg){}\n:::\n:::\n\n\n\nThe η = 1000 EBCM is compared directly with the committed *mass-action* ensemble of\n`:sir_wm5` (NetworkOutbreaks' `MassActionSSA`):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(wm, refwm)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_wm5`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refwm, limit[end], detwm; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_wm5  (scenario 6e8fb963; conditioned mean of 200 runs)\n  curve                  observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  EBCM η = 1000.0        I            0.00136     14.25   0.00101      2.16  -0.00049  [-0.00170,  0.00072]   0.00057      0.00     0.954\n  EBCM η = 1000.0        cumulative   0.00363     16.25   0.00267      1.48  -0.00049  [-0.00170,  0.00072]  -0.00049      0.00     1.000\n  mass action (β = 1/2)  I            0.00143     14.25   0.00101      2.22  -0.00043  [-0.00164,  0.00078]   0.00062      0.00     0.929\n  mass action (β = 1/2)  cumulative   0.00384     16.25   0.00267      1.57  -0.00043  [-0.00164,  0.00078]  -0.00043      0.00     1.000\n```\n:::\n:::\n\n\n\n## A Poisson base tends to MFSH, not to mass action\n\nOn a base whose degrees vary, fast exchange does *not* give mass action. A node of degree k keeps\nk stubs, so it still meets k/⟨k⟩ times as many partners per unit time as an average node. High-degree\nnodes are both more likely to be infected and more infectious. MSV Part II call the η → ∞ limit\n*mean-field social heterogeneity* (MFSH); EdgeBasedModels has it as `MFSHNetwork(d)` (see\n[E16](../E16_dormant_fleeting/index.qmd)). The scenario `:sir_ne_pois5_eta10` is neighbour\nexchange at η = 10 on a Poisson(5) base, with the same τ = 1/12 and γ = 1/4:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsp = scenario(:sir_ne_pois5_eta10)\n@assert isequivalent(model, sp.model)\nrefp = scenario_summary(sp)\nsysp = edge_based(model, sp.network)\ndetp = model_curves(sysp, solve_epidemic(sysp, sp); t = sp.tgrid, label = \"edge-based (DFD, Poisson base)\")\nmf = scenario(:sir_mfsh_pois5)\nsysm = edge_based(model, mf.network)\ndetm = model_curves(sysm, solve_epidemic(sysm, mf); t = sp.tgrid, label = \"MFSH (η → ∞)\")\np = comparisonplot(refp, detp, detm; observables = [:I, :cumulative])\nstyle_curves!(p, [(:royalblue, :solid), (:crimson, :dash)], [detp.label, detm.label])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-21-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sp, refp)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_ne_pois5_eta10`: N = 5000, 100 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 100 major runs, P(major) = 1.000 (95% CI 0.963–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refp, detp, detm; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_ne_pois5_eta10  (scenario 48abf545; conditioned mean of 100 runs)\n  curve                           observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (DFD, Poisson base)  I            0.00234     17.00   0.00174      2.16   0.00126  [-0.00200,  0.00453]   0.00195      0.00     0.968\n  edge-based (DFD, Poisson base)  cumulative   0.00611     19.50   0.00456      1.62   0.00126  [-0.00200,  0.00453]   0.00126      4.50     1.000\n  MFSH (η → ∞)                    I            0.00701     14.25   0.00174      5.28   0.00798  [ 0.00472,  0.01125]   0.00563     -0.50     0.536\n  MFSH (η → ∞)                    cumulative   0.02225     19.50   0.00456      5.71   0.00798  [ 0.00472,  0.01125]   0.00798      4.50     0.010\n```\n:::\n:::\n\n\n\nThe final sizes of the three limits:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmdtable([\"model\", \"R∞\"],\n        [(\"DFD η = 10, Poisson(5) base (EBCM)\", detp[:cumulative][end]),\n         (\"NetworkOutbreaks, same scenario (major runs)\", mean(refp.final_size[refp.major])),\n         (\"MFSH, Poisson(5) activity (η → ∞)\", final_size(sysm; p = mf.params, initial = mf.initial)),\n         (\"mass action β = 5τ = 5/12 (what a naive limit would give)\",\n          final_size(edge_based(model, WellMixed(5.0)); p = Dict(:τ => 1 / 12, :γ => 1 / 4),\n                     initial = sp.initial))])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|                                                     model |     R∞ |\n| ---------------------------------------------------------:| ------:|\n|                        DFD η = 10, Poisson(5) base (EBCM) | 0.6619 |\n|              NetworkOutbreaks, same scenario (major runs) | 0.6607 |\n|                         MFSH, Poisson(5) activity (η → ∞) | 0.6687 |\n| mass action β = 5τ = 5/12 (what a naive limit would give) | 0.6827 |\n\n:::\n:::\n\n\n\nThe mass-action row uses β = ⟨k⟩τ = 5/12. Its R₀ = β/γ and that of the MFSH limit,\nτ(κ_ex + 1)/γ, are:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(; mass_action = (5 / 12) / (1 / 4), MFSH_formula = mf.params[:τ] * (excess_degree(PoissonDegree(5)) + 1) / mf.params[:γ],\n   MFSH_EBCM = basic_reproduction_number(sysm; p = mf.params), MFSH_registry = mf.expected[:R0])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(mass_action = 1.6666666666666667, MFSH_formula = 2.0, MFSH_EBCM = 2.0, MFSH_registry = 2.0)\n```\n:::\n:::\n\n\n\nThe MFSH R₀ is 2, as for `:sir_wm5`, but its final size (0.669 above) is smaller than the\nmass-action value in the η → ∞ table of the previous section. The high-activity nodes are\ninfected early and removed, so the epidemic runs out of fuel sooner. At η = 10 the Poisson-base\nEBCM is still visibly short of its limit (compare the two rows of the table), and the simulation\nfollows the finite-η model, not the limit. On a regular base κ_ex + 1 = k, and MFSH *is* mass action\nwith β = kτ, which is why the 6-regular sweep above ends at `:sir_wm5`.\n\n## Lean\n\nNone of the dynamic-network statements on this page is formalised; the checks are the symbolic\ntest against MSV's equations and the simulations above.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-commonmark"
    ],
    "filters": [],
    "includes": {}
  }
}