import Alignment.Registry
-- Worked example and self-test mocks (ids EXAMPLE.* / SELFTEST.*, excluded from normal reports)
import Alignment.Example.ExampleShadows
import Alignment.Example.ExampleChecks
import Alignment.Example.SelfTest
-- Groups: add `import Alignment.Shadows.<Group>` and `import Alignment.Checks.<Group>` here
import Alignment.Shadows.CategoricalComposition
import Alignment.Checks.CategoricalComposition
import Alignment.Shadows.ClosureTheorem
import Alignment.Checks.ClosureTheorem
import Alignment.Shadows.ClusteringExtension
import Alignment.Checks.ClusteringExtension
import Alignment.Shadows.CoarseGrain
import Alignment.Checks.CoarseGrain
import Alignment.Shadows.ConvergenceTheorems
import Alignment.Checks.ConvergenceTheorems
import Alignment.Shadows.DegreeCorrelation
import Alignment.Checks.DegreeCorrelation
import Alignment.Shadows.Docs
import Alignment.Checks.Docs
import Alignment.Shadows.DynamicLimits
import Alignment.Checks.DynamicLimits
import Alignment.Shadows.EpiCategory
import Alignment.Checks.EpiCategory
import Alignment.Shadows.GaloisPair
import Alignment.Checks.GaloisPair
import Alignment.Shadows.Hierarchy
import Alignment.Checks.Hierarchy
import Alignment.Shadows.InvariantRegion
import Alignment.Checks.InvariantRegion
import Alignment.Shadows.MarginalisationCharacterization
import Alignment.Checks.MarginalisationCharacterization
import Alignment.Shadows.MarginalisationDynamicalGap
import Alignment.Checks.MarginalisationDynamicalGap
import Alignment.Shadows.MarginalisationFunctor
import Alignment.Checks.MarginalisationFunctor
import Alignment.Shadows.MessagePassingBridge
import Alignment.Checks.MessagePassingBridge
import Alignment.Shadows.MethodOfStages
import Alignment.Checks.MethodOfStages
import Alignment.Shadows.Obstructions
import Alignment.Checks.Obstructions
import Alignment.Shadows.PairwiseClosureConditions
import Alignment.Checks.PairwiseClosureConditions
import Alignment.Shadows.SEIREquations
import Alignment.Checks.SEIREquations
import Alignment.Shadows.SurvivalBridge
import Alignment.Checks.SurvivalBridge
import Alignment.Shadows.VolzMeyersEquations
import Alignment.Checks.VolzMeyersEquations
-- Review records (must come last: it imports the modules that declare bridges)
import Alignment.ReviewedBridges
