{
  "hash": "15c13b5d958ee245fbb683f62868b60a",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"E10. Multitype populations, stratification and heterogeneous susceptibility\"\nsubtitle: \"Typed edge-based models on stochastic block models and unstructured networks, reciprocity, the unit law, and susceptible classes\"\n---\n\n## What this page shows\n\nA population split into types (age groups, risk groups) is described twice: in the **model**, by\nstratifying the reaction network over the types (`stratify`), and in the **network**, by a\n`MultitypeNetwork` that gives each type a joint degree law over partner types. The edge-based\nlift then has one θ for every (partner type, own type) pair\n[@miller2013incorporating]. This page:\n\n1. builds the stratified SIR on a two-block Poisson stochastic block model (`:sir_sbm2`) twice\n   and compares it with NetworkOutbreaks' typed simulation;\n2. shows the error for degree laws that no network can realise (edge reciprocity);\n3. checks the unit law: types that the network ignores give back the untyped model\n   (`:sir_unstr2` = `:sir_reg6`);\n4. models **heterogeneous susceptibility**: several susceptible classes sharing I and R\n   (`:sir_hetsus_bim`, `:seirv_hetsus_pois5`), against NetworkOutbreaks.\n\nIts NodeBasedModels mirror is page N04, on the same `:sir_sbm2` summary.\n\n## The shared first cell\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nusing Statistics\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nsir = @reaction_network sir begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ; S converted, I unchanged\n    γ, I --> R             # node-local transition\nend\nmodel = contact_model(sir)          # prints the typing report\nst    = strata([:a, :b]; sizes = [0.5, 0.5])\nmodel_ab = stratify(model, st)      # S_a + I_b → I_a + I_b, I_a → R_a, …\nsc    = scenario(:sir_sbm2)         # Poisson SBM, mean contacts [6 2; 2 4], τ calibrated to R₀ = 2\n@assert isequivalent(model_ab, sc.model)\nref   = scenario_summary(sc)        # committed typed NetworkOutbreaks ensemble\n# --- EBM vignette ---------------------------------------------------------------\nusing EdgeBasedModels\nnet   = sbm_network(st; mean_contacts = [6.0 2.0; 2.0 4.0])\nsys   = edge_based(model_ab, net)                          # low level\nsysF  = edge_based(sc)                                     # scenario form (model and network from the registry)\n@assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\nlift_contributions(model_ab, net)                          # per-reaction terms on the typed network\n```\n\n::: {#shared-cell .cell-output .cell-output-display execution_count=1}\n```\nLiftContributions :sir_strat on NetworkEpiCore.MultitypeNetwork([:a, :b], [0.5, 0.5], NetworkEpiCore.MultivariateDegree[NetworkEpiCore.IndependentDegrees(Pair[:a => NetworkEpiCore.PoissonDegree(6.0), :b => NetworkEpiCore.PoissonDegree(2.0)]), NetworkEpiCore.IndependentDegrees(Pair[:a => NetworkEpiCore.PoissonDegree(2.0), :b => NetworkEpiCore.PoissonDegree(4.0)])], Bool[0 0; 0 0])  (multitype closure)\n  coordinates  θ_a_a, θ_b_a, ξ_S_a, θ_a_b, θ_b_b, ξ_S_b, φ_I_a_a, φ_I_a_b, φ_I_b_a, φ_I_b_b, φ_R_a_a, φ_R_a_b, φ_R_b_a, φ_R_b_b, pop_I_a, pop_I_b, pop_R_a, pop_R_b\n  seed factors q_S_a (initially susceptible fraction of S_a), q_S_b (initially susceptible fraction of S_b)\n  [1] S_a + I_a → 2I_a  (τ)   contact\n        θ_a_a'    += -φ_I_a_a*τ\n        φ_I_a_a'  += -φ_I_a_a*τ\n        φ_I_a_a'  += 6*q_S_a*exp(6.0(-1 + θ_a_a))*ξ_S_a*φ_I_a_a*exp(2.0(-1 + θ_b_a))*τ\n        φ_I_a_b'  += 6*q_S_a*exp(6.0(-1 + θ_a_a))*ξ_S_a*φ_I_a_a*exp(2.0(-1 + θ_b_a))*τ\n        pop_I_a'  += 3.0q_S_a*exp(6.0(-1 + θ_a_a))*ξ_S_a*φ_I_a_a*exp(2.0(-1 + θ_b_a))*τ\n  [2] S_a + I_b → I_a + I_b  (τ)   contact\n        θ_b_a'    += -φ_I_b_a*τ\n        φ_I_b_a'  += -φ_I_b_a*τ\n        φ_I_a_a'  += 2*q_S_a*exp(6.0(-1 + θ_a_a))*ξ_S_a*φ_I_b_a*exp(2.0(-1 + θ_b_a))*τ\n        φ_I_a_b'  += 2*q_S_a*exp(6.0(-1 + θ_a_a))*ξ_S_a*φ_I_b_a*exp(2.0(-1 + θ_b_a))*τ\n        pop_I_a'  += q_S_a*exp(6.0(-1 + θ_a_a))*ξ_S_a*φ_I_b_a*exp(2.0(-1 + θ_b_a))*τ\n  [3] S_b + I_a → I_b + I_a  (τ)   contact\n        θ_a_b'    += -φ_I_a_b*τ\n        φ_I_a_b'  += -φ_I_a_b*τ\n        φ_I_b_a'  += 2*q_S_b*exp(4.0(-1 + θ_b_b))*φ_I_a_b*ξ_S_b*exp(2.0(-1 + θ_a_b))*τ\n        φ_I_b_b'  += 2*q_S_b*exp(4.0(-1 + θ_b_b))*φ_I_a_b*ξ_S_b*exp(2.0(-1 + θ_a_b))*τ\n        pop_I_b'  += q_S_b*exp(4.0(-1 + θ_b_b))*φ_I_a_b*ξ_S_b*exp(2.0(-1 + θ_a_b))*τ\n  [4] S_b + I_b → 2I_b  (τ)   contact\n        θ_b_b'    += -φ_I_b_b*τ\n        φ_I_b_b'  += -φ_I_b_b*τ\n        φ_I_b_a'  += 4*q_S_b*φ_I_b_b*exp(4.0(-1 + θ_b_b))*ξ_S_b*exp(2.0(-1 + θ_a_b))*τ\n        φ_I_b_b'  += 4*q_S_b*φ_I_b_b*exp(4.0(-1 + θ_b_b))*ξ_S_b*exp(2.0(-1 + θ_a_b))*τ\n        pop_I_b'  += 2.0q_S_b*φ_I_b_b*exp(4.0(-1 + θ_b_b))*ξ_S_b*exp(2.0(-1 + θ_a_b))*τ\n  [5] I_a → R_a  (γ)   progress\n        φ_I_a_a'  += -φ_I_a_a*γ\n        φ_R_a_a'  += φ_I_a_a*γ\n        φ_I_a_b'  += -φ_I_a_b*γ\n        φ_R_a_b'  += φ_I_a_b*γ\n        pop_I_a'  += -pop_I_a*γ\n        pop_R_a'  += pop_I_a*γ\n  [6] I_b → R_b  (γ)   progress\n        φ_I_b_a'  += -φ_I_b_a*γ\n        φ_R_b_a'  += φ_I_b_a*γ\n        φ_I_b_b'  += -φ_I_b_b*γ\n        φ_R_b_b'  += φ_I_b_b*γ\n        pop_I_b'  += -pop_I_b*γ\n        pop_R_b'  += pop_I_b*γ\n```\n:::\n:::\n\n\n\n`stratify` makes one copy of every species per stratum and one contact for every pair of strata\n(susceptible of type a, infector of type b). With the default `contact_rates = :same` every\ncontact keeps the per-contact rate τ. What differs between the types is the *number* of contacts,\nand that lives in the network.\n\n## The typed network and its lifted equations\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nshow(stdout, MIME\"text/plain\"(), net); println()\nprintln(\"mean contacts of an a-node: \", [mean_degree(net.degrees[1], b) for b in net.types])\nprintln(\"mean contacts of a b-node: \", [mean_degree(net.degrees[2], b) for b in net.types])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMultitypeNetwork with 2 types\n  :a  size 0.5  IndependentDegrees(parts=[:a => PoissonDegree(mean=6), :b => PoissonDegree(mean=2)])\n  :b  size 0.5  IndependentDegrees(parts=[:a => PoissonDegree(mean=2), :b => PoissonDegree(mean=4)])\n  structural zeros: none\nmean contacts of an a-node: [6.0, 2.0]\nmean contacts of a b-node: [2.0, 4.0]\n```\n:::\n:::\n\n\n\nThere are four θ's. `θ_b_a` belongs to an edge from a b-partner to an a-node, and the φ's are\nindexed the same way (`φ_I_b_a`: the b-partner is infected and has not yet transmitted). The\nnode variables are per type:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(sys)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :edge_based_model_edge_based (16 states)\n  dθ_a_a/dt = -φ_I_a_a(t)*τ\n  dθ_b_a/dt = -φ_I_b_a(t)*τ\n  dθ_a_b/dt = -φ_I_a_b(t)*τ\n  dθ_b_b/dt = -φ_I_b_b(t)*τ\n  dφ_I_a_a/dt = -φ_I_a_a(t)*γ - φ_I_a_a(t)*τ + (6//1)*q_S_a*exp(6.0(-1 + θ_a_a(t)))*φ_I_a_a(t)*exp(2.0(-1 + θ_b_a(t)))*τ + (2//1)*q_S_a*exp(6.0(-1 + θ_a_a(t)))*φ_I_b_a(t)*exp(2.0(-1 + θ_b_a(t)))*τ\n  dφ_I_a_b/dt = -φ_I_a_b(t)*γ - φ_I_a_b(t)*τ + (6//1)*q_S_a*exp(6.0(-1 + θ_a_a(t)))*φ_I_a_a(t)*exp(2.0(-1 + θ_b_a(t)))*τ + (2//1)*q_S_a*exp(6.0(-1 + θ_a_a(t)))*φ_I_b_a(t)*exp(2.0(-1 + θ_b_a(t)))*τ\n  dφ_I_b_a/dt = -φ_I_b_a(t)*γ - φ_I_b_a(t)*τ + (4//1)*q_S_b*φ_I_b_b(t)*exp(4.0(-1 + θ_b_b(t)))*exp(2.0(-1 + θ_a_b(t)))*τ + (2//1)*q_S_b*exp(4.0(-1 + θ_b_b(t)))*φ_I_a_b(t)*exp(2.0(-1 + θ_a_b(t)))*τ\n  dφ_I_b_b/dt = -φ_I_b_b(t)*γ - φ_I_b_b(t)*τ + (4//1)*q_S_b*φ_I_b_b(t)*exp(4.0(-1 + θ_b_b(t)))*exp(2.0(-1 + θ_a_b(t)))*τ + (2//1)*q_S_b*exp(4.0(-1 + θ_b_b(t)))*φ_I_a_b(t)*exp(2.0(-1 + θ_a_b(t)))*τ\n  dφ_R_a_a/dt = φ_I_a_a(t)*γ\n  dφ_R_a_b/dt = φ_I_a_b(t)*γ\n  dφ_R_b_a/dt = φ_I_b_a(t)*γ\n  dφ_R_b_b/dt = φ_I_b_b(t)*γ\n  dpop_I_a/dt = -pop_I_a(t)*γ + 3.0q_S_a*exp(6.0(-1 + θ_a_a(t)))*φ_I_a_a(t)*exp(2.0(-1 + θ_b_a(t)))*τ + q_S_a*exp(6.0(-1 + θ_a_a(t)))*φ_I_b_a(t)*exp(2.0(-1 + θ_b_a(t)))*τ\n  dpop_I_b/dt = -pop_I_b(t)*γ + 2.0q_S_b*φ_I_b_b(t)*exp(4.0(-1 + θ_b_b(t)))*exp(2.0(-1 + θ_a_b(t)))*τ + q_S_b*exp(4.0(-1 + θ_b_b(t)))*φ_I_a_b(t)*exp(2.0(-1 + θ_a_b(t)))*τ\n  dpop_R_a/dt = pop_I_a(t)*γ\n  dpop_R_b/dt = pop_I_b(t)*γ\n  parameters  τ, γ, q_S_a, q_S_b\n  domain      θ_a_a ∈ (0.05, 1.0)\n  domain      θ_b_a ∈ (0.05, 1.0)\n  domain      θ_a_b ∈ (0.05, 1.0)\n  domain      θ_b_b ∈ (0.05, 1.0)\n```\n:::\n:::\n\n\n\nAn a-node is still susceptible with probability q_{S_a} ∏_c exp(μ_{ac}(θ_c_a − 1)), where μ_{ac}\nis its mean number of c-partners. That factor multiplies the gain terms of `φ_I_a_a` and\n`φ_I_a_b` alike: on independent Poisson blocks, the rate at which an a-partner is infected does\nnot depend on the type of the node at the other end of the edge.\n\n### R₀ from the next-generation matrix\n\nτ was calibrated so that the spectral radius of the next-generation matrix is 2. On Poisson\nblocks the NGM is τ/(τ + γ) times the mean-contact matrix M, and ρ(M) = 7.236:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nusing LinearAlgebra\nM = [6.0 2.0; 2.0 4.0]\nT = sc.params[:τ] / (sc.params[:τ] + sc.params[:γ])\n(; τ = sc.params[:τ], ρM = maximum(abs.(eigvals(M))), T_ρM = T * maximum(abs.(eigvals(M))),\n   NEC = basic_reproduction_number(sc.model, sc.network, sc.params),\n   EBCM = basic_reproduction_number(sys; p = sc.params))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(τ = 0.09549150281, ρM = 7.23606797749979, T_ρM = 1.999999999961713, NEC = 1.9999999999617124, EBCM = 1.999999999961713)\n```\n:::\n:::\n\n\n\n## Typed EBCM against typed simulation\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsol = solve_epidemic(sys, sc)\ndet = model_curves(sys, sol; t = sc.tgrid, label = \"edge-based (multitype)\")\ncomparisonplot(ref, det; observables = [:I_a, :I_b, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-6-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sc, ref)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_sbm2`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(ref, det)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_sbm2  (scenario f8e96436; conditioned mean of 200 runs)\n  curve                   observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (multitype)  S_a          0.00120      9.00   0.00126      1.93   0.00111  [-0.00009,  0.00231]   0.00000      0.00     1.000\n  edge-based (multitype)  S_b          0.00089     31.25   0.00105      2.02   0.00111  [-0.00009,  0.00231]   0.00000      0.00     0.975\n  edge-based (multitype)  I_a          0.00113     16.50   0.00060      3.31   0.00111  [-0.00009,  0.00231]   0.00078      0.25     0.905\n  edge-based (multitype)  I_b          0.00071     15.00   0.00048      2.39   0.00111  [-0.00009,  0.00231]   0.00033      0.00     0.971\n  edge-based (multitype)  R_a          0.00091     11.75   0.00099      1.75   0.00111  [-0.00009,  0.00231]   0.00040      0.00     1.000\n  edge-based (multitype)  R_b          0.00086     37.50   0.00087      1.98   0.00111  [-0.00009,  0.00231]   0.00072      0.00     0.979\n  edge-based (multitype)  infectious   0.00172     15.00   0.00100      3.31   0.00111  [-0.00009,  0.00231]   0.00111      0.25     0.917\n  edge-based (multitype)  cumulative   0.00147     19.25   0.00223      2.20   0.00111  [-0.00009,  0.00231]   0.00111      0.00     0.851\n```\n:::\n:::\n\n\n\nBlock a has more contacts (6 + 2 against 2 + 4), so its epidemic peaks higher and earlier:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nia, ib = det[:I_a] ./ 0.5, det[:I_b] ./ 0.5          # within-type prevalence\nmdtable([\"type\", \"peak within-type prevalence\", \"time of the peak\", \"final within-type size\"],\n        [(\"a\", maximum(ia), sc.tgrid[argmax(ia)], det[:R_a][end] / 0.5),\n         (\"b\", maximum(ib), sc.tgrid[argmax(ib)], det[:R_b][end] / 0.5)])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n| type | peak within-type prevalence | time of the peak | final within-type size |\n| ----:| ---------------------------:| ----------------:| ----------------------:|\n|    a |                      0.2149 |               13 |                 0.8325 |\n|    b |                      0.1728 |               14 |                 0.7171 |\n\n:::\n:::\n\n\n\n## Reciprocity: degree laws that no network realises\n\nEvery edge between the types has one end in each. So the number of a→b edge ends,\nN n_a E[k_{a→b}], must equal the number of b→a ends, N n_b E[k_{b→a}]. A mean-contact matrix that\nbreaks this describes no network, and the constructor says so:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntry\n    sbm_network(st; mean_contacts = [6.0 3.0; 2.0 4.0])\ncatch e\n    print(sprint(showerror, e))\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nArgumentError: MultitypeNetwork: edge reciprocity n_a·E[k_{a→b}] = n_b·E[k_{b→a}] fails (rtol = 1.0e-8), so no network realises these degree laws. Mismatches:\n  a ↔ b:  n_a·E[k_{a→b}] = 0.5 × 3 = 1.5   vs   n_b·E[k_{b→a}] = 0.5 × 2 = 1\n```\n:::\n:::\n\n\n\nThe same matrix is reciprocal for sizes 0.4 and 0.6 (0.4 × 3 = 0.6 × 2). That is the age-structured\nscenario `:sir_age2`:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nst46 = strata([:y, :o]; sizes = [0.4, 0.6])\nsbm_network(st46; mean_contacts = [6.0 3.0; 2.0 4.0])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nMultitypeNetwork with 2 types\n  :y  size 0.4  IndependentDegrees(parts=[:y => PoissonDegree(mean=6), :o => PoissonDegree(mean=3)])\n  :o  size 0.6  IndependentDegrees(parts=[:y => PoissonDegree(mean=2), :o => PoissonDegree(mean=4)])\n  structural zeros: none\n```\n:::\n:::\n\n\n\n## The unit law: an unstructured typed network\n\nIf the types are only labels, so that a node's partners are of type b with probability n_b\nwhatever its own type, the typed model must reproduce the untyped one. This is morphism M10 in\nDESIGN §D.5. `unstructured(net, st)` builds that network. `:sir_unstr2` is the stratified SIR on\nan unstructured 6-regular network, and its aggregate should equal `:sir_reg6`:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsu = scenario(:sir_unstr2)\n@assert isequivalent(model_ab, su.model)\nrefu = scenario_summary(su)\nsysu = edge_based(model_ab, unstructured(ConfigurationNetwork(RegularDegree(6)), st))\n@assert vector_fields_equal(symbolic_ode(sysu), symbolic_ode(edge_based(su)))\ntol = (; reltol = 1e-10, abstol = 1e-12)\nsolu = solve_epidemic(sysu, su; tol...)\ndetu = model_curves(sysu, solu; t = su.tgrid, label = \"edge-based (typed, unstructured)\")\n\ns6 = scenario(:sir_reg6)\n@assert isequivalent(model, s6.model)\nsys6 = edge_based(model, s6.network)\ndet6 = model_curves(sys6, solve_epidemic(sys6, s6; tol...); t = s6.tgrid, label = \"edge-based (untyped, 6-regular)\")\n(; max_S = maximum(abs.(detu[:S_a] .+ detu[:S_b] .- det6[:S])),\n   max_I = maximum(abs.(detu[:I_a] .+ detu[:I_b] .- det6[:I])),\n   max_cumulative = maximum(abs.(detu[:cumulative] .- det6[:cumulative])))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(max_S = 4.901634653720066e-14, max_I = 4.5075054799781356e-14, max_cumulative = 6.994405055138486e-14)\n```\n:::\n:::\n\n\n\nThe typed and untyped curves agree to within the solver tolerance (10⁻¹⁰ relative), and both agree with their own ensembles:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(su, refu)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_unstr2`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refu, detu; observables = [:I_a, :I_b, :infectious, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_unstr2  (scenario 8ae47e8f; conditioned mean of 200 runs)\n  curve                             observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (typed, unstructured)  I_a          0.00056     11.50   0.00058      1.93  -0.00004  [-0.00061,  0.00052]   0.00034      0.00     1.000\n  edge-based (typed, unstructured)  I_b          0.00046      8.50   0.00057      1.38  -0.00004  [-0.00061,  0.00052]   0.00017      0.00     1.000\n  edge-based (typed, unstructured)  infectious   0.00093     11.50   0.00111      1.85  -0.00004  [-0.00061,  0.00052]   0.00051      0.00     1.000\n  edge-based (typed, unstructured)  cumulative   0.00096      8.50   0.00212      0.97  -0.00004  [-0.00061,  0.00052]  -0.00004      5.75     1.000\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nref6 = scenario_summary(s6)\nreference_note(s6, ref6)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_reg6`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(ref6, det6; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_reg6  (scenario e5443b54; conditioned mean of 200 runs)\n  curve                            observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (untyped, 6-regular)  I            0.00171     10.00   0.00117      2.74   0.00026  [-0.00027,  0.00080]   0.00128     -0.25     0.975\n  edge-based (untyped, 6-regular)  cumulative   0.00191     11.50   0.00225      1.67   0.00026  [-0.00027,  0.00080]   0.00026      5.50     1.000\n```\n:::\n:::\n\n\n\n## Heterogeneous susceptibility\n\nSusceptibility often varies between people for reasons unrelated to their contacts (prior\nimmunity, age, genetics). @miller2013incorporating [§2.2.2] model it with\nseveral susceptible classes sharing the same network. In NetworkEpiCore the classes are\nsusceptible species labelled by the strata of `unstructured(net, st)`, and I and R are shared\n(unlabelled). EdgeBasedModels lifts them with its *heterogeneous* closure, which keeps one θ_a and one φ_{Y,a}\nper class a (the edge into a class-a node), not the K² edge types θ_{b→a} of the full multitype\nlift.\n\n### SIR on the bimodal network\n\n`:sir_hetsus_bim` has 40% of nodes with τ = 0.05 and 60% with τ = 0.3, on the bimodal {2, 10}\nnetwork of `:sir_bim` (a non-Poisson-type network). The model is written with the direct\nconstructor, since a species label is not a Catalyst concept:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nlab(x, a) = SpeciesLabel(x; stratum = a)\nhet = ContactModel(:sir_het;\n    contacts = [Contact(:S_lo, :I, :I, :τ_lo), Contact(:S_hi, :I, :I, :τ_hi)],\n    transitions = [NodeTransition(:I, :R, :γ)],\n    labels = Dict(:S_lo => lab(:S, :lo), :S_hi => lab(:S, :hi)))\nsh = scenario(:sir_hetsus_bim)\n@assert isequivalent(het, sh.model)\nrefh = scenario_summary(sh)\nhs = strata([:lo, :hi]; sizes = [0.4, 0.6])\nbim = ConfigurationNetwork(EmpiricalDegree(2 => 5 / 6, 10 => 1 / 6))\nsysh = edge_based(het, bim, hs)                            # low level: model, base network, strata\n@assert vector_fields_equal(symbolic_ode(sysh), symbolic_ode(edge_based(sh)))   # scenario form\nlift_contributions(het, bim, hs)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nLiftContributions :sir_het on NetworkEpiCore.MultitypeNetwork([:lo, :hi], [0.4, 0.6], NetworkEpiCore.MultivariateDegree[NetworkEpiCore.SplitDegrees(NetworkEpiCore.EmpiricalDegree([0.0, 0.0, 0.8333333333333334, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16666666666666666]), [:lo => 0.4, :hi => 0.6]), NetworkEpiCore.SplitDegrees(NetworkEpiCore.EmpiricalDegree([0.0, 0.0, 0.8333333333333334, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.16666666666666666]), [:lo => 0.4, :hi => 0.6])], Bool[0 0; 0 0])  (heterogeneous closure)\n  coordinates  θ_lo, ξ_S_lo, θ_hi, ξ_S_hi, φ_I_lo, φ_I_hi, φ_R_lo, φ_R_hi, pop_I, pop_R\n  seed factors q_S_lo (initially susceptible fraction of S_lo), q_S_hi (initially susceptible fraction of S_hi)\n  [1] S_lo + I → 2I  (τ_lo)   contact\n        θ_lo'    += -φ_I_lo*τ_lo\n        φ_I_lo'  += -φ_I_lo*τ_lo\n        φ_I_lo'  += 0.12000000000000002q_S_lo*ξ_S_lo*(1.6666666666666667 + 15.0(θ_lo^8))*φ_I_lo*τ_lo\n        φ_I_hi'  += 0.12000000000000002q_S_lo*ξ_S_lo*(1.6666666666666667 + 15.0(θ_lo^8))*φ_I_lo*τ_lo\n        pop_I'   += 0.4q_S_lo*ξ_S_lo*(1.6666666666666667θ_lo + 1.6666666666666665(θ_lo^9))*φ_I_lo*τ_lo\n  [2] S_hi + I → 2I  (τ_hi)   contact\n        θ_hi'    += -φ_I_hi*τ_hi\n        φ_I_hi'  += -φ_I_hi*τ_hi\n        φ_I_lo'  += 0.18000000000000002q_S_hi*(1.6666666666666667 + 15.0(θ_hi^8))*ξ_S_hi*φ_I_hi*τ_hi\n        φ_I_hi'  += 0.18000000000000002q_S_hi*(1.6666666666666667 + 15.0(θ_hi^8))*ξ_S_hi*φ_I_hi*τ_hi\n        pop_I'   += 0.6q_S_hi*(1.6666666666666667θ_hi + 1.6666666666666665(θ_hi^9))*ξ_S_hi*φ_I_hi*τ_hi\n  [3] I → R  (γ)   progress\n        φ_I_lo'  += -φ_I_lo*γ\n        φ_R_lo'  += φ_I_lo*γ\n        φ_I_hi'  += -φ_I_hi*γ\n        φ_R_hi'  += φ_I_hi*γ\n        pop_I'   += -pop_I*γ\n        pop_R'   += pop_I*γ\n```\n:::\n:::\n\n\n\nThe per-class entry factor is q_{S_a} ψ′(θ_a)/ψ′(1), and a class-a susceptible adds its node\ncount n_a q_{S_a} ψ(θ_a) to S. A **negative control** is the homogeneous model with the\nclass-averaged rate τ̄ = 0.4 · 0.05 + 0.6 · 0.3 = 0.2:\n\nThe shared recipe `comparisonplot` styles every curve by its representation, so two edge-based\ncurves would come out in the same colour. `style_curves!` gives each curve of a comparison figure its\nown colour and dash, in the order the curves were passed:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    style_curves!(p, styles) -> p\n\nGive the model curves of a `comparisonplot` figure `p` their own line colours and styles.\n`styles` holds one `(linecolor, linestyle)` pair per curve, in the order the curves were passed.\nThe recipe draws the curves last in every panel, so they are the last `length(styles)` series of\neach subplot; the labels of the first panel are checked against `labels`.\n\"\"\"\nfunction style_curves!(p, styles, labels)\n    n = length(styles)\n    first_labels = [s[:label] for s in p.subplots[1].series_list[end-n+1:end]]\n    first_labels == collect(labels) ||\n        error(\"style_curves!: the last series of the first panel are $(first_labels), not $(labels)\")\n    for sp in p.subplots, (k, (lc, ls)) in enumerate(styles)\n        s = sp.series_list[end-n+k]\n        s[:linecolor] = Plots.plot_color(lc)\n        s[:linestyle] = ls\n    end\n    return p\nend\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nMain.Notebook.style_curves!\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsolh = solve_epidemic(sysh, sh)\ndeth = model_curves(sysh, solh; t = sh.tgrid, label = \"edge-based (heterogeneous τ)\")\nτbar = 0.4 * sh.params[:τ_lo] + 0.6 * sh.params[:τ_hi]\nsysbar = edge_based(model, bim)\nsolbar = solve_epidemic(sysbar; p = Dict(:τ => τbar, :γ => sh.params[:γ]), initial = sh.initial,\n                        tspan = sh.tspan, saveat = sh.tgrid)\ndetbar = model_curves(sysbar, solbar; t = sh.tgrid, label = \"homogeneous, τ̄ = $(τbar)\")\np = comparisonplot(refh, deth, detbar; observables = [:I, :cumulative], legend = :right)\nstyle_curves!(p, [(:royalblue, :solid), (:crimson, :dash)], [deth.label, detbar.label])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-19-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sh, refh)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_hetsus_bim`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refh, deth; observables = [:S_lo, :S_hi, :I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_hetsus_bim  (scenario c0ce2b90; conditioned mean of 200 runs)\n  curve                         observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (heterogeneous τ)  S_lo         0.00084     10.50   0.00034      2.55   0.00132  [-0.00051,  0.00315]  -0.00005      0.00     0.769\n  edge-based (heterogeneous τ)  S_hi         0.00362      9.50   0.00122      3.15   0.00132  [-0.00051,  0.00315]   0.00005      0.00     0.686\n  edge-based (heterogeneous τ)  I            0.00218      8.00   0.00080      3.04   0.00132  [-0.00051,  0.00315]   0.00164     -0.50     0.793\n  edge-based (heterogeneous τ)  cumulative   0.00444      9.50   0.00150      3.04   0.00132  [-0.00051,  0.00315]   0.00132      0.50     0.694\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refh, deth, detbar; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_hetsus_bim  (scenario c0ce2b90; conditioned mean of 200 runs)\n  curve                         observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (heterogeneous τ)  I            0.00218      8.00   0.00080      3.04   0.00132  [-0.00051,  0.00315]   0.00164     -0.50     0.793\n  edge-based (heterogeneous τ)  cumulative   0.00444      9.50   0.00150      3.04   0.00132  [-0.00051,  0.00315]   0.00132      0.50     0.694\n  homogeneous, τ̄ = 0.2          I            0.05734      9.00   0.00080    107.47   0.13255  [ 0.13073,  0.13438]   0.05725     -0.50     0.256\n  homogeneous, τ̄ = 0.2          cumulative   0.14381     15.50   0.00150    143.83   0.13255  [ 0.13073,  0.13438]   0.13256      0.50     0.017\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nWith two classes the EBCM follows the simulation (D∞(I) = 0.0022, ΔR∞ = +0.0013). The mean-susceptibility model misses it (D∞(I) = 0.0573, ΔR∞ = +0.1326); its R₀ is compared with the heterogeneous one below.\n\n:::\n:::\n\n\n\nThe two R₀'s: the heterogeneous one is κ_ex Σ_a n_a T_a, where T_a = τ_a/(τ_a + γ), while the\nhomogeneous one is κ_ex T(τ̄):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nκ = excess_degree(bim)\nTf(τ) = τ / (τ + sh.params[:γ])\n(; heterogeneous = κ * (0.4 * Tf(sh.params[:τ_lo]) + 0.6 * Tf(sh.params[:τ_hi])),\n   registry = sh.expected[:R0], EBCM = basic_reproduction_number(sysh; p = sh.params),\n   homogeneous_mean_τ = κ * Tf(τbar))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(heterogeneous = 1.96969696969697, registry = 1.9696969696969697, EBCM = 1.96969696969697, homogeneous_mean_τ = 2.2222222222222228)\n```\n:::\n:::\n\n\n\n### The quotient of the stratified model (M10)\n\nThe heterogeneous model is the quotient of the full multitype lift of the *stratified* model on\nthe same unstructured network, where I and R are also split by class. The node totals therefore\nagree, to within the solver tolerance:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nstrat = stratify(model, hs; contact_rates = (a, b) -> a === :lo ? :τ_lo : :τ_hi)\nsysM = edge_based(strat, unstructured(bim, hs))\nsolM = solve_epidemic(sysM; p = sh.params, initial = SeedFraction(:I_lo => 0.004, :I_hi => 0.006),\n                      tspan = sh.tspan, saveat = sh.tgrid, tol...)\nsolh2 = solve_epidemic(sysh, sh; tol...)\nIM = compartment(sysM, solM, :I_lo) .+ compartment(sysM, solM, :I_hi)\n(; max_I = maximum(abs.(IM .- compartment(sysh, solh2, :I))),\n   max_S_lo = maximum(abs.(compartment(sysM, solM, :S_lo) .- compartment(sysh, solh2, :S_lo))),\n   coordinates_heterogeneous = length(symbolic_ode(sysh).states),\n   coordinates_multitype = length(symbolic_ode(sysM).states))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(max_I = 2.607289384393141e-14, max_S_lo = 6.050715484207103e-15, coordinates_heterogeneous = 8, coordinates_multitype = 16)\n```\n:::\n:::\n\n\n\nThe 1% shared seeds in I are placed on every type in proportion to its size (§J.6), hence\n`:I_lo => 0.004, :I_hi => 0.006` in the stratified model.\n\n### SEIR with class-specific latency and vaccination\n\n`:seirv_hetsus_pois5` has class-specific latent stages E_lo, E_hi, a shared I and R, vaccination\nof the high-susceptibility class S_hi → V at rate ν, and removal of the vaccinated at rate μ, on\nPoisson(5):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsv = scenario(:seirv_hetsus_pois5)\nsv.model\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nContactModel :seirv_het  (source: ContactModel constructor; method: explicit; rates: PerContact)\n  species       S_lo (Sus)   S_hi (Sus)   E_lo   I   E_hi   R   V\n  contacts      [1] S_lo + I → E_lo + I    τ_lo    contact     infector I, entry E_lo\n                [2] S_hi + I → E_hi + I    τ_hi    contact     infector I, entry E_hi\n  transitions   [3] E_lo → I               σ_lo    progress\n                [4] E_hi → I               σ_hi    progress\n                [5] I → R                  γ       progress\n                [6] S_hi → V               ν       exit\n                [7] V → ∅                  μ       remove\n  typing        T_EB  ⇒  edge_based ✓  s_anchored ✓  pairwise ✓  individual ✓  pair ✓  stochastic ✓  mass_action ✓\n  assumptions   Sus inferred as recipients \\ contact products = {S_lo, S_hi}\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrefv = scenario_summary(sv)\nsysv = edge_based(sv.model, ConfigurationNetwork(PoissonDegree(5)), hs)\n@assert vector_fields_equal(symbolic_ode(sysv), symbolic_ode(edge_based(sv)))\ndetv = model_curves(sysv, solve_epidemic(sysv, sv); t = sv.tgrid, label = \"edge-based (heterogeneous SEIR-V)\")\ncomparisonplot(refv, detv; observables = [:I, :V, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-27-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sv, refv)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:seirv_hetsus_pois5`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refv, detv; observables = [:S_lo, :S_hi, :E_lo, :E_hi, :I, :V, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :seirv_hetsus_pois5  (scenario f50b8c3e; conditioned mean of 200 runs)\n  curve                              observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (heterogeneous SEIR-V)  S_lo         0.00088     35.00   0.00069      1.75   0.00079  [-0.00109,  0.00266]  -0.00005      0.00     1.000\n  edge-based (heterogeneous SEIR-V)  S_hi         0.00187     25.00   0.00118      2.11   0.00079  [-0.00109,  0.00266]   0.00005      0.00     0.950\n  edge-based (heterogeneous SEIR-V)  E_lo         0.00019     22.00   0.00010      1.85   0.00079  [-0.00109,  0.00266]  -0.00008      0.00     1.000\n  edge-based (heterogeneous SEIR-V)  E_hi         0.00091     20.00   0.00036      2.99   0.00079  [-0.00109,  0.00266]   0.00074      0.00     0.876\n  edge-based (heterogeneous SEIR-V)  I            0.00077     25.00   0.00044      2.89   0.00079  [-0.00109,  0.00266]   0.00034      0.00     0.926\n  edge-based (heterogeneous SEIR-V)  V            0.00045     28.00   0.00021      2.18   0.00079  [-0.00109,  0.00266]  -0.00016      0.00     0.942\n  edge-based (heterogeneous SEIR-V)  cumulative   0.00302     31.00   0.00195      1.76   0.00079  [-0.00109,  0.00266]   0.00079      1.00     1.000\n```\n:::\n:::\n\n\n\nThe exit from S_hi means there is no final-size fixed point, so R∞ is read from the ODE at the\nend of the time span. ΔR∞ above is that value minus the ensemble's mean final size.\n\n## Summary\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrows = map([(ref, det, :I_a), (refu, detu, :I_a), (refh, deth, :I), (refv, detv, :I)]) do (r, c, X)\n    row = compare(r, c; observables = [X])[c.label, X]\n    (string(\"`:\", r.id, \"`\"), string(X), row.D∞, row.z∞, row.ΔR∞)\nend\nmdtable([\"scenario\", \"observable\", \"D∞\", \"z∞\", \"ΔR∞\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|              scenario | observable |        D∞ |    z∞ |        ΔR∞ |\n| ---------------------:| ----------:| ---------:| -----:| ----------:|\n|           `:sir_sbm2` |        I_a |  0.001132 | 3.311 |   0.001109 |\n|         `:sir_unstr2` |        I_a | 0.0005645 | 1.935 | -4.156e-05 |\n|     `:sir_hetsus_bim` |          I |  0.002183 | 3.045 |   0.001321 |\n| `:seirv_hetsus_pois5` |          I | 0.0007656 | 2.891 |  0.0007853 |\n\n:::\n:::\n\n\n\n## Lean\n\nNone of the multitype statements on this page is formalised.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-commonmark"
    ],
    "filters": [],
    "includes": {}
  }
}