{
  "hash": "16f3fa0e7bc010d3acb27b390226e6d2",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"E13. Where edge-based models stop: SIS and SIRS\"\nsubtitle: \"Why an edge-based model cannot represent reinfection, and what the node-based approximations give against simulation\"\n---\n\n## What this page shows\n\nAn edge-based model keeps one number θ per edge: the probability that the edge has not yet\ntransmitted. That is enough when a node, once infected, never becomes susceptible again. Then a\nnode is susceptible exactly when no edge has transmitted to it, so S = q ψ(θ). If recovered nodes\nreturn to S (SIS, SIRS), a node can be susceptible after an edge *has* transmitted to it, and\nthe edges of a node are no longer independent. Miller, Slim and Volz state this as the scope of\nthe method [@miller2012edge]. The typing layer refuses these models and names the back ends that\naccept them. This page:\n\n1. shows the refusal for `:sis_reg3` and `:sirs_pois5`, with the typing reports and the error\n   texts;\n2. compares the node-based (pairwise, motif and neighbourhood) approximations of NodeBasedModels\n   with NetworkOutbreaks' SIS simulation, conditioned on survival. This is the same comparison as\n   NodeBasedModels' page N12;\n3. does the same for SIRS with the constant-closure pairwise model.\n\n## The shared first cell\n\n::: {#shared-cell .cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nusing Statistics\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nsis = @reaction_network sis begin\n    @parameters τ γ\n    τ, S + I --> 2I        # contact: per-contact (per-edge) rate τ\n    γ, I --> S             # recovery back into the susceptible class (type resus)\nend\nmodel = contact_model(sis)          # prints the typing report: T_net, not T_EB\nsc    = scenario(:sis_reg3)         # 3-regular, τ = 1/2, γ = 1/4, 1% seeds in I, t ∈ [0, 80]\n@assert isequivalent(model, sc.model)\nref   = scenario_summary(sc)        # committed NetworkOutbreaks ensemble, conditioned on survival\n# --- EBM vignette ---------------------------------------------------------------\nusing EdgeBasedModels\nerr = try\n    edge_based(model, sc.network)                          # low level: refused\ncatch e\n    e\nend\n@assert err isa AdmissibilityError\nprint(sprint(showerror, err))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAdmissibilityError: edge_based(:sis, ConfigurationNetwork(RegularDegree(3))):\n  `γ, I --> S` (type resus: node → sus) produces the susceptible species S.\n  The edge-based model is exact only when no reaction produces a susceptible class\n  (Miller, Slim & Volz 2012, Part I). Back ends that accept this model: node_based\n  (pairwise, individual, pair, motif, neighbourhood), simulate, mass_action.\n  Try: NodeBasedModels.node_based(model, net; closure = KeelingClosure()).\n```\n:::\n:::\n\n\n\nThe factory refuses too, with a migration message:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntry\n    build_sis(RegularDegree(3), :τ, :γ)\ncatch e\n    print(sprint(showerror, e))\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nbuild_sis returned SIR dynamics relabelled (ebm-core #1, verified issue E01): its θ equation was Miller's SIR equation and its I was the cumulative incidence. SIS has no exact edge-based model (an arrow into the susceptible class breaks the edge-based construction; Miller, Slim & Volz 2012). Use NodeBasedModels.node_based(sis_model(), net) (pairwise closures, reinfection counting with with_reinfection_counting) or NetworkOutbreaks.simulate(sis_model(), net; …) (exact stochastic simulation).\n```\n:::\n:::\n\n\n\nThe typing report of the model says why. The reaction `γ, I --> S` has type `resus`, which is in\nT_net but not in the edge-based fragment T_EB:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmodel\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nContactModel :sis  (source: Catalyst.ReactionSystem; method: stoichiometry; rates: PerContact)\n  species       S (Sus)   I\n  contacts      [1] S + I → I + I    τ    contact    infector I, entry I\n  transitions   [2] I → S            γ    resus\n  typing        T_net  ⇒  edge_based ✗  s_anchored ✗  pairwise ✓  individual ✓  pair ✓  stochastic ✓  mass_action ✓\n  violations    `γ, I --> S` (type resus: node → sus) produces the susceptible species S.\n  assumptions   Sus inferred as recipients \\ contact products = {S}\n```\n:::\n:::\n\n\n\nNo Lean theorem is cited for this refusal. It is a rule of the typing (a `resus` reaction is\noutside T_EB), and it is tested: NetworkEpiCore's test set \"T_EB and the transition types\"\n(`test/suites/ir_typing.jl`) checks that T_EB is {contact, exit, progress, remove} and that a\n`resus` violation blocks the edge-based back ends, and EdgeBasedModels' test set \"E19: SIS, SIRS\nand reinfection-counted models are refused by every closure\" (`test/suites/lift_errors.jl`)\nchecks that `edge_based` refuses SIS and SIRS on every network type. This is a statement about\nthe syntax only, not a proof that no edge-based semantics for reinfection can exist.\n\nSIRS is refused for the same reason (`ε, R --> S`):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsirs = @reaction_network sirs begin\n    @parameters τ γ ε\n    τ, S + I --> 2I\n    γ, I --> R\n    ε, R --> S             # waning immunity (type resus)\nend\nsr = scenario(:sirs_pois5)          # Poisson(5), τ = 1/6, γ = 1/4, ε = 1/50, t ∈ [0, 300]\n@assert isequivalent(contact_model(sirs), sr.model)\ntry\n    edge_based(contact_model(sirs), sr.network)\ncatch e\n    print(sprint(showerror, e))\nend\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAdmissibilityError: edge_based(:sirs, ConfigurationNetwork(PoissonDegree(5.0))):\n  `ε, R --> S` (type resus: node → sus) produces the susceptible species S.\n  The edge-based model is exact only when no reaction produces a susceptible class\n  (Miller, Slim & Volz 2012, Part I). Back ends that accept this model: node_based\n  (pairwise, individual, pair, motif, neighbourhood), simulate, mass_action.\n  Try: NodeBasedModels.node_based(model, net; closure = KeelingClosure()).\n```\n:::\n:::\n\n\n\n## SIS: node-based approximations against simulation\n\nThe scenario lists the back ends that accept SIS, each with its status:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsort(collect(sc.backends); by = first)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n7-element Vector{Pair{Symbol, Symbol}}:\n         :edge_based => :inadmissible\n              :motif => :approximate\n      :neighbourhood => :approximate\n :pairwise_bernoulli => :approximate\n     :pairwise_const => :approximate\n        :pgf_closure => :inadmissible\n        :reinfection => :approximate\n```\n:::\n:::\n\n\n\nThe error message points to `node_based`. NodeBasedModels builds the population pairwise model\n(Bernoulli closure on a regular network), the motif closures of order m = 2, 3, 4 and the\nneighbourhood model with n = 2 [@keeling1999effects]. The motif and neighbourhood systems are\nsolved with their own solvers, and their prevalence is wrapped as `ModelCurves` on the scenario\ngrid.\n\nThe shared recipe `comparisonplot` styles a curve by its representation; `style_curves!` gives each\ncurve of a comparison figure its own colour and dash, in the order the curves were passed:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    style_curves!(p, styles) -> p\n\nGive the model curves of a `comparisonplot` figure `p` their own line colours and styles.\n`styles` holds one `(linecolor, linestyle)` pair per curve, in the order the curves were passed.\nThe recipe draws the curves last in every panel, so they are the last `length(styles)` series of\neach subplot; the labels of the first panel are checked against `labels`.\n\"\"\"\nfunction style_curves!(p, styles, labels)\n    n = length(styles)\n    first_labels = [s[:label] for s in p.subplots[1].series_list[end-n+1:end]]\n    first_labels == collect(labels) ||\n        error(\"style_curves!: the last series of the first panel are $(first_labels), not $(labels)\")\n    for sp in p.subplots, (k, (lc, ls)) in enumerate(styles)\n        s = sp.series_list[end-n+k]\n        s[:linecolor] = Plots.plot_color(lc)\n        s[:linestyle] = ls\n    end\n    return p\nend\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nMain.Notebook.style_curves!\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nimport NodeBasedModels as NBM\npw  = NBM.node_based(sc; closure = NBM.BernoulliClosure())\ncpw = model_curves(pw, solve_epidemic(pw, sc); t = sc.tgrid, label = \"pairwise (Bernoulli)\")\nfunction motif_curves(m)\n    s = NBM.node_based(sc; level = :motif, closure = NBM.MotifClosure(3, m))\n    sol = NBM.solve_motif(s; saveat = sc.tgrid)\n    ModelCurves(sc.tgrid, Dict(:I => compartment(s, sol, :I)); label = \"motif m = $(m)\", representation = :motif)\nend\ncm2, cm3, cm4 = motif_curves(2), motif_curves(3), motif_curves(4)\nnb  = NBM.node_based(sc; level = :neighbourhood, n = 2)\ncnb = ModelCurves(sc.tgrid, Dict(:I => NBM.neighbourhood_compartment(nb, NBM.solve_neighbourhood(nb; saveat = sc.tgrid), :I));\n                  label = \"neighbourhood n = 2\", representation = :neighbourhood)\napprox = [cpw, cm2, cm3, cm4, cnb]\n# one colour and dash per approximation, in both figures of this section (see `style_curves!` below)\nstyles = [(:darkorange, :dash), (:forestgreen, :dot), (:teal, :dashdot), (:royalblue, :solid), (:crimson, :solid)]\np = comparisonplot(ref, approx...; observables = [:I])\nstyle_curves!(p, styles, [c.label for c in approx])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-8-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sc, ref)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sis_reg3`: N = 10000, 200 runs (a fresh graph per run), conditioned on Survival(); 200 surviving runs, P(survival) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntab = compare(ref, approx; observables = [:I])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sis_reg3  (scenario 485d890e; conditioned mean of 200 runs)\n  curve                 observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  pairwise (Bernoulli)  I            0.14556      9.50   0.00160     93.69  14.70400  [14.70400, 14.70400]  -0.00023      4.25     0.153\n  motif m = 2           I            0.14556      9.50   0.00160     93.69       NaN  [     NaN,      NaN]  -0.00023      1.75     0.153\n  motif m = 3           I            0.06009      9.75   0.00160     39.65       NaN  [     NaN,      NaN]  -0.00025    -17.50     0.202\n  motif m = 4           I            0.00888     10.75   0.00160     11.27       NaN  [     NaN,      NaN]  -0.00016    -15.50     0.688\n  neighbourhood n = 2   I            0.02525     10.75   0.00160     21.41       NaN  [     NaN,      NaN]  -0.00106     37.75     0.769\n```\n:::\n:::\n\n\n\nThe ΔR∞ column is meaningless here. It compares cumulative incidence, which for SIS counts\nreinfections, and only the pairwise curves carry it. The transient and the endemic level are the\nquantities to compare:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nst = ref.cond[:I]\nrows = map(approx) do c\n    row = tab[c.label, :I]\n    (c.label, row.D∞, row.t_D∞, c[:I][end], c[:I][end] - st.mean[end], row.z∞)\nend\npush!(rows, (\"NetworkOutbreaks (mean of surviving runs)\", 0.0, NaN, st.mean[end], 0.0, NaN))\nmdtable([\"approximation\", \"D∞(I)\", \"t at D∞\", \"I(80)\", \"I(80) − SSA\", \"z∞\"], rows)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|                             approximation |    D∞(I) | t at D∞ |  I(80) | I(80) − SSA |    z∞ |\n| -----------------------------------------:| --------:| -------:| ------:| -----------:| -----:|\n|                      pairwise (Bernoulli) |   0.1456 |     9.5 | 0.8182 |    0.001126 | 93.69 |\n|                               motif m = 2 |   0.1456 |     9.5 | 0.8182 |    0.001126 | 93.69 |\n|                               motif m = 3 |  0.06009 |    9.75 | 0.8163 |  -0.0007423 | 39.65 |\n|                               motif m = 4 | 0.008878 |   10.75 | 0.8174 |   0.0003262 | 11.27 |\n|                       neighbourhood n = 2 |  0.02525 |   10.75 | 0.8173 |   0.0002934 | 21.41 |\n| NetworkOutbreaks (mean of surviving runs) |        0 |     NaN | 0.8171 |           0 |   NaN |\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nAt t = 80 every approximation is within 0.0011 of the simulated endemic prevalence 0.8171, whose standard error is 0.00030. They differ in the transient, where the epidemic takes off: the closest over the whole time course is motif m = 4 (D∞(I) = 0.0089), and the pairwise curve is up to 0.1456 from the simulated mean. The motif closure with m = 2 *is* Keeling's pairwise closure; its curve differs from the pairwise one by at most 1.7e-09. This page does not establish what causes the transient gap. Moment-closure error is one candidate, but a timing offset of this kind can also come from the initial condition (the ODEs start from an uncorrelated pair state around a small seed, while each simulated run starts from explicit seeded nodes whose neighbourhoods are not yet correlated in the same way) or from the comparison itself: the reference is the mean over surviving runs with no time alignment, so run-to-run variation in when the epidemic takes off flattens and delays the mean curve. The endemic level at t = 80 should be insensitive to both, and there the approximations agree with the simulation to within the values in the I(80) − SSA column.\n\n:::\n:::\n\n\n\nThe early epidemic, where the approximations differ most:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\np = plot(ref, :I; median = false, legend = :bottomright, title = \"SIS on a 3-regular network, early phase\")\nfor (c, (lc, ls)) in zip(approx, styles)\n    plot!(p, c, :I; linecolor = lc, linestyle = ls)\nend\nxlims!(p, 0, 30)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-13-output-1.svg){}\n:::\n:::\n\n\n\n## SIRS: the constant-closure pairwise model\n\nFor SIRS on Poisson(5) NodeBasedModels' default is the pairwise model with the constant closure\nK = ⟨k(k−1)⟩/⟨k⟩² = 1, which is exact for SIR on a Poisson network but only an approximation once\nimmunity wanes:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nrefr = scenario_summary(sr)\npr = NBM.node_based(sr)\ncpr = model_curves(pr, solve_epidemic(pr, sr); t = sr.tgrid, label = \"pairwise (K = 1)\")\ncomparisonplot(refr, cpr; observables = [:I, :R])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-commonmark/cell-14-output-1.svg){}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sr, refr)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sirs_pois5`: N = 10000, 200 runs (a fresh graph per run), conditioned on Survival(); 198 surviving runs, P(survival) = 0.990 (95% CI 0.964–0.997).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(refr, cpr; observables = [:S, :I, :R])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sirs_pois5  (scenario c4098584; conditioned mean of 198 runs)\n  curve             observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  pairwise (K = 1)  S            0.02032     89.00   0.00345      6.15   2.16161  [ 2.16133,  2.16190]   0.00000      0.00     0.226\n  pairwise (K = 1)  I            0.00469    106.00   0.00119      5.43   2.16161  [ 2.16133,  2.16190]   0.00104      0.00     0.688\n  pairwise (K = 1)  R            0.01793     94.00   0.00301      6.20   2.16161  [ 2.16133,  2.16190]   0.00238      0.00     0.226\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nstr = refr.cond[:I]\nmdtable([\"quantity\", \"pairwise (K = 1)\", \"NetworkOutbreaks (surviving runs)\", \"SE of the mean\"],\n        [(\"I(300)\", cpr[:I][end], str.mean[end], str.se[end]),\n         (\"peak I\", maximum(cpr[:I]), maximum(str.mean), NaN),\n         (\"time of the peak\", sr.tgrid[argmax(cpr[:I])], sr.tgrid[argmax(str.mean)], NaN)])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|         quantity | pairwise (K = 1) | NetworkOutbreaks (surviving runs) | SE of the mean |\n| ----------------:| ----------------:| ---------------------------------:| --------------:|\n|           I(300) |          0.03513 |                           0.03535 |       0.000558 |\n|           peak I |           0.2399 |                            0.2388 |            NaN |\n| time of the peak |               12 |                                12 |            NaN |\n\n:::\n:::\n\n\n\n## Where to go instead\n\n- NodeBasedModels' pages N09–N12 treat SIS in depth: reinfection counting (N09), motif closures\n  (N10), the neighbourhood model (N11) and all of them against simulation (N12).\n- NetworkOutbreaks simulates any T_net model exactly on explicit graphs.\n- For models with waning immunity *and* a large effect of network structure, simulation is the\n  reference; the pairwise model above is a fast approximation whose error is printed on this page.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [],
    "includes": {}
  }
}