{
  "hash": "aa9b67bd99def5f7831163978cb99e58",
  "result": {
    "engine": "julia",
    "markdown": "---\ntitle: \"E11. Multiplex networks\"\nsubtitle: \"Contacts on several layers of the same nodes: layer metadata, the multiplex EBCM, and R₀ = ρ(K)\"\n---\n\n## What this page shows\n\nPeople meet at home and in the community, and the two kinds of contact have different numbers\nand different transmission rates. A **multiplex** network puts several independent configuration\nlayers on the same nodes. The EBCM keeps one θ_ℓ per layer, and a node escapes infection only\nif it escapes on every layer, so S = q ∏_ℓ ψ_ℓ(θ_ℓ). In NetworkEpiCore a contact names its layer.\nIn Catalyst it is reaction metadata `[layer = :home]`, and in the direct constructor it is\n`Contact(…; layer = :home)`. This page:\n\n1. builds the two-layer scenario `:sir_mpx` from a Catalyst network with layer metadata, and with\n   the factory `build_multiplex_sir`;\n2. shows that the basic reproduction number is the spectral radius ρ(K) of a 2 × 2\n   next-generation matrix, not the sum of the layer R₀'s;\n3. compares the EBCM with NetworkOutbreaks' multiplex simulation.\n\n## The shared first cell\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ninclude(joinpath(@__DIR__, \"..\", \"_shared\", \"setup.jl\"))\nusing Statistics, LinearAlgebra\nusing NetworkEpiCore, NetworkOutbreaks, Catalyst, Plots\nsir_mpx = @reaction_network sir_mpx begin\n    @parameters c γ\n    3c, S + I --> 2I, [layer = :home]   # household contacts: per-contact rate 3c\n    c, S + I --> 2I, [layer = :comm]    # community contacts: per-contact rate c\n    γ, I --> R                          # node-local: happens once, on every layer\nend\nmodel = contact_model(sir_mpx)      # prints the typing report\nsc    = scenario(:sir_mpx)          # home: 3-regular, community: Poisson(5); c calibrated to R₀ = 2\n@assert isequivalent(model, sc.model)\nref   = scenario_summary(sc)        # committed NetworkOutbreaks multiplex ensemble\n# --- EBM vignette ---------------------------------------------------------------\nusing EdgeBasedModels\nnet   = MultiplexNetwork(:home => RegularDegree(3), :comm => PoissonDegree(5))\nsys   = edge_based(model, net)                             # low level\nsysF  = build_multiplex_sir(:home => (RegularDegree(3), :(3c)), :comm => (PoissonDegree(5), :c); γ = :γ)\n@assert vector_fields_equal(symbolic_ode(sys), symbolic_ode(sysF))\nlift_contributions(model, net)                             # per-reaction, per-layer terms\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nLiftContributions :sir_mpx on NetworkEpiCore.MultiplexNetwork(Pair[:home => NetworkEpiCore.ConfigurationNetwork(NetworkEpiCore.RegularDegree(3)), :comm => NetworkEpiCore.ConfigurationNetwork(NetworkEpiCore.PoissonDegree(5.0))])  (multiplex closure)\n  coordinates  θ_home, θ_comm, ξ, φ_I_home, φ_I_comm, φ_R_home, φ_R_comm, pop_I, pop_R\n  seed factors q_S (initially susceptible fraction of S)\n  [1] S + I → 2I  (3c)   contact\n        θ_home'    += -3c*φ_I_home\n        φ_I_home'  += -3c*φ_I_home\n        φ_I_home'  += 6*c*q_S*φ_I_home*θ_home*exp(5.0(-1 + θ_comm))*ξ\n        φ_I_comm'  += 9*c*q_S*φ_I_home*(θ_home^2)*exp(5.0(-1 + θ_comm))*ξ\n        pop_I'     += 9c*q_S*φ_I_home*(θ_home^2)*exp(5.0(-1 + θ_comm))*ξ\n  [2] S + I → 2I  (c)   contact\n        θ_comm'    += -c*φ_I_comm\n        φ_I_comm'  += -c*φ_I_comm\n        φ_I_home'  += 5*c*q_S*φ_I_comm*(θ_home^2)*exp(5.0(-1 + θ_comm))*ξ\n        φ_I_comm'  += 5*c*q_S*φ_I_comm*(θ_home^3)*exp(5.0(-1 + θ_comm))*ξ\n        pop_I'     += 5.0c*q_S*φ_I_comm*(θ_home^3)*exp(5.0(-1 + θ_comm))*ξ\n  [3] I → R  (γ)   progress\n        φ_I_home'  += -φ_I_home*γ\n        φ_R_home'  += φ_I_home*γ\n        φ_I_comm'  += -φ_I_comm*γ\n        φ_R_comm'  += φ_I_comm*γ\n        pop_I'     += -pop_I*γ\n        pop_R'     += pop_I*γ\n```\n:::\n:::\n\n\n\nThe scenario:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nprintln(sc.title)\nprintln(\"parameters: c = \", sc.params[:c], \", γ = \", sc.params[:γ],\n        \"; so τ_home = \", 3sc.params[:c], \", τ_comm = \", sc.params[:c])\nprintln(\"seeding: \", sc.initial, \";  t ∈ \", sc.tspan)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSIR on a two-layer multiplex (household 3-regular, community Poisson(5))\nparameters: c = 0.05970959492, γ = 0.25; so τ_home = 0.17912878476, τ_comm = 0.05970959492\nseeding: SeedFraction([:I => 0.01], nothing);  t ∈ (0.0, 80.0)\n```\n:::\n:::\n\n\n\n## The lifted equations\n\nEach contact acts only on the edges of its own layer. The progression I → R is node-local, so it\nmoves φ_{I,ℓ} to φ_{R,ℓ} on every layer:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsymbolic_ode(sys)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nSymbolicODE :edge_based_model_edge_based (8 states)\n  dθ_home/dt = -3c*φ_I_home(t)\n  dθ_comm/dt = -c*φ_I_comm(t)\n  dφ_I_home/dt = -3c*φ_I_home(t) - φ_I_home(t)*γ + (6//1)*c*q_S*φ_I_home(t)*θ_home(t)*exp(5.0(-1 + θ_comm(t))) + (5//1)*c*q_S*φ_I_comm(t)*(θ_home(t)^2)*exp(5.0(-1 + θ_comm(t)))\n  dφ_I_comm/dt = -c*φ_I_comm(t) - φ_I_comm(t)*γ + (9//1)*c*q_S*φ_I_home(t)*(θ_home(t)^2)*exp(5.0(-1 + θ_comm(t))) + (5//1)*c*q_S*φ_I_comm(t)*(θ_home(t)^3)*exp(5.0(-1 + θ_comm(t)))\n  dφ_R_home/dt = φ_I_home(t)*γ\n  dφ_R_comm/dt = φ_I_comm(t)*γ\n  dpop_I/dt = -pop_I(t)*γ + 9c*q_S*φ_I_home(t)*(θ_home(t)^2)*exp(5.0(-1 + θ_comm(t))) + 5.0c*q_S*φ_I_comm(t)*(θ_home(t)^3)*exp(5.0(-1 + θ_comm(t)))\n  dpop_R/dt = pop_I(t)*γ\n  parameters  c, γ, q_S\n  domain      θ_home ∈ (0.05, 1.0)\n  domain      θ_comm ∈ (0.05, 1.0)\n```\n:::\n:::\n\n\n\nA susceptible node of degrees (k_home, k_comm) is still susceptible with probability\nq θ_home^{k_home} θ_comm^{k_comm}. The partner at the end of a home edge is therefore\nsusceptible with probability φ_{S,home} = q ψ_home′(θ_home) ψ_comm(θ_comm)/ψ_home′(1), and the\ngain terms of φ_{I,home} carry ψ_home″(θ_home) ψ_comm(θ_comm)/ψ_home′(1). On the 3-regular home\nlayer that is 6θ_home e^{5(θ_comm − 1)}/3, the factor printed above. The partner at the end of a home edge carries on\ninfecting along its community edges too, which is how the layers are coupled.\n\n## R₀ = ρ(K), not the sum of the layer R₀'s\n\nLinearising at the disease-free state gives a next-generation matrix over layers\n[@jacobsen2018large]. A case infected along a layer-m edge produces T_ℓ ψ_ℓ″(1)/ψ_ℓ′(1)\nnew layer-ℓ cases if ℓ = m, and T_ℓ ψ_ℓ′(1) if ℓ ≠ m, where T_ℓ = τ_ℓ/(τ_ℓ + γ) is the per-edge\ntransmissibility. With K_{ℓm} the number of new layer-ℓ cases per layer-m case,\nK = [[T₁e₁, T₁k₁], [T₂k₂, T₂e₂]], where e_ℓ = ψ_ℓ″(1)/ψ_ℓ′(1) and k_ℓ = ψ_ℓ′(1). The 0.1 package returned the sum of the diagonal, the \"additive\" R₀. That is\nwrong unless det K = 0:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nc, γ = sc.params[:c], sc.params[:γ]\nT = [3c / (3c + γ), c / (c + γ)]\nd = [RegularDegree(3), PoissonDegree(5)]\nk = [mean_degree(x) for x in d]                         # ψ′(1): 3, 5\ne = [excess_degree(x) for x in d]                       # ψ″(1)/ψ′(1): 2, 5\nK = [T[1] * e[1] T[1] * k[1]; T[2] * k[2] T[2] * e[2]]\n(; K, ρK = maximum(abs.(eigvals(K))), additive = T[1] * e[1] + T[2] * e[2], detK = det(K))\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(K = [0.8348486101214666 1.2522729151821999; 0.9639610121769616 0.9639610121769616], ρK = 2.0000000000956146, additive = 1.7988096222984282, detK = -0.40238075561360925)\n```\n:::\n:::\n\n\n\nThe same numbers come from NetworkEpiCore's next-generation engine (the registry value, over\n(layer, entry) blocks), from the lifted ODE, and from the legacy `multiplex_R0`, which now also\nreturns ρ(K):\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nmdtable([\"source\", \"R₀\"],\n        [(\"ρ(K), by hand\", maximum(abs.(eigvals(K)))),\n         (\"NetworkEpiCore NGM (scenario expected value)\", sc.expected[:R0]),\n         (\"EBCM, `basic_reproduction_number(sys; p)`\", basic_reproduction_number(sys; p = sc.params)),\n         (\"`multiplex_R0` (0.1 tuple form)\", multiplex_R0([(:home, RegularDegree(3), 3c, γ), (:comm, PoissonDegree(5), c, γ)])),\n         (\"additive (sum of layer R₀'s), wrong\", sc.expected[:R0_additive])])\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\n|                                       source |    R₀ |\n| --------------------------------------------:| -----:|\n|                                ρ(K), by hand |     2 |\n| NetworkEpiCore NGM (scenario expected value) |     2 |\n|    EBCM, `basic_reproduction_number(sys; p)` |     2 |\n|              `multiplex_R0` (0.1 tuple form) |     2 |\n|          additive (sum of layer R₀'s), wrong | 1.799 |\n\n:::\n:::\n\n\n\nThe 2 × 2 formula ρ(K) = (K₁₁ + K₂₂ + √((K₁₁ − K₂₂)² + 4K₁₂K₂₁))/2 is proved in Lean for\nK₁₁ ≥ 0, K₂₂ ≥ 0 and K₁₂K₂₁ ≥ 0, and applied to the two-layer matrix\nK = [[T₁e₁, T₁k₁], [T₂k₂, T₂e₂]], taking that matrix as given:\n\n``` {.julia .cell-code}\nfor n in (\"NEP.spectralRadius_fin_two\", \"NEP.multiplex_r0_of_entries\")\n    display(lean_cite(n))\nend\n```\nLean: `NEP.spectralRadius_fin_two`\n\nLean: `NEP.multiplex_r0_of_entries`\n\n\n\n\nThe same Lean file proves, under the same entry conditions, that ρ(K) equals the additive value\nT₁e₁ + T₂e₂ if and only if (T₁k₁)(T₂k₂) = (T₁e₁)(T₂e₂). When T₁T₂ ≠ 0 this is k₁k₂ = e₁e₂, which holds for independent\nPoisson layers, where k_ℓ = e_ℓ:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nlean_cite(\"NEP.multiplex_r0_eq_sum_iff_of_entries\")\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nLean: `NEP.multiplex_r0_eq_sum_iff_of_entries`\n\n:::\n:::\n\n\n\nHere k₁k₂ = 15 and e₁e₂ = 10, so the additive value is off:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n(; k1k2 = k[1] * k[2], e1e2 = e[1] * e[2],\n   relative_error_of_additive = (sc.expected[:R0_additive] - sc.expected[:R0]) / sc.expected[:R0])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(k1k2 = 15.0, e1e2 = 10.0, relative_error_of_additive = -0.10059518889378402)\n```\n:::\n:::\n\n\n\nAs a check of the \"if\" direction, take two Poisson layers. The two values then agree:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nKp(τ1, τ2, μ1, μ2) = (T1 = τ1 / (τ1 + γ); T2 = τ2 / (τ2 + γ); [T1 * μ1 T1 * μ1; T2 * μ2 T2 * μ2])\nKpo = Kp(0.3, 0.1, 3.0, 5.0)\n(; ρK = maximum(abs.(eigvals(Kpo))), additive = Kpo[1, 1] + Kpo[2, 2])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n(ρK = 3.064935064935065, additive = 3.064935064935065)\n```\n:::\n:::\n\n\n\n## EBCM against the multiplex simulation\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsol = solve_epidemic(sys, sc)\ndet = model_curves(sys, sol; t = sc.tgrid, label = \"edge-based (multiplex)\")\ncomparisonplot(ref, det; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-11-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nreference_note(sc, ref)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nNetworkOutbreaks reference `:sir_mpx`: N = 10000, 200 runs (a fresh graph per run), conditioned on MajorOutbreak(0.05); 200 major runs, P(major) = 1.000 (95% CI 0.981–1.000).\n\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ntab = compare(ref, det)\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_mpx  (scenario 688c01dd; conditioned mean of 200 runs)\n  curve                   observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (multiplex)  S            0.00130     12.25   0.00215      1.05  -0.00020  [-0.00104,  0.00064]   0.00000      0.00     1.000\n  edge-based (multiplex)  I            0.00080      9.75   0.00104      1.18  -0.00020  [-0.00104,  0.00064]   0.00032      0.00     1.000\n  edge-based (multiplex)  R            0.00097     15.50   0.00167      1.19  -0.00020  [-0.00104,  0.00064]  -0.00020      1.75     1.000\n  edge-based (multiplex)  infectious   0.00080      9.75   0.00104      1.18  -0.00020  [-0.00104,  0.00064]   0.00032      0.00     1.000\n  edge-based (multiplex)  cumulative   0.00129     12.25   0.00215      1.05  -0.00020  [-0.00104,  0.00064]  -0.00020      8.75     1.000\n```\n:::\n:::\n\n\n\nFor contrast, take a *single-layer* model with the same total degree distribution (3 plus a\nPoisson(5) number of contacts, mean 8), and choose its one per-contact rate so that its R₀ is\nalso 2:\n\nThe shared recipe `comparisonplot` styles every curve by its representation, so two edge-based\ncurves would come out in the same colour. `style_curves!` gives each curve of a comparison figure its\nown colour and dash, in the order the curves were passed:\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\n\"\"\"\n    style_curves!(p, styles) -> p\n\nGive the model curves of a `comparisonplot` figure `p` their own line colours and styles.\n`styles` holds one `(linecolor, linestyle)` pair per curve, in the order the curves were passed.\nThe recipe draws the curves last in every panel, so they are the last `length(styles)` series of\neach subplot; the labels of the first panel are checked against `labels`.\n\"\"\"\nfunction style_curves!(p, styles, labels)\n    n = length(styles)\n    first_labels = [s[:label] for s in p.subplots[1].series_list[end-n+1:end]]\n    first_labels == collect(labels) ||\n        error(\"style_curves!: the last series of the first panel are $(first_labels), not $(labels)\")\n    for sp in p.subplots, (k, (lc, ls)) in enumerate(styles)\n        s = sp.series_list[end-n+k]\n        s[:linecolor] = Plots.plot_color(lc)\n        s[:linestyle] = ls\n    end\n    return p\nend\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nMain.Notebook.style_curves!\n```\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\nsingle = ConfigurationNetwork(EmpiricalDegree(Dict(3 + j => exp(-5.0) * 5.0^j / factorial(big(j)) for j in 0:40)))\nκs = excess_degree(single)\nτs = 2γ / (κs - 2)          # T κ_ex = 2 with T = τ/(τ + γ)\nsys1 = edge_based(sir_model(), single)\ndet1 = model_curves(sys1, solve_epidemic(sys1; p = Dict(:τ => τs, :γ => γ), initial = sc.initial,\n                                         tspan = sc.tspan, saveat = sc.tgrid);\n                    t = sc.tgrid, label = \"one layer, R₀ = 2\")\np = comparisonplot(ref, det, det1; observables = [:I, :cumulative], legend = :right)\nstyle_curves!(p, [(:royalblue, :solid), (:crimson, :dash)], [det.label, det1.label])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n![](index_files/figure-pdf/cell-15-output-1.svg){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell execution_count=1}\n``` {.julia .cell-code}\ncompare(ref, det, det1; observables = [:I, :cumulative])\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\nComparisonTable :sir_mpx  (scenario 688c01dd; conditioned mean of 200 runs)\n  curve                   observable        D∞     t(D∞)       SE∞        z∞       ΔR∞  95% CI                 Δpeak   Δt_peak  coverage\n  edge-based (multiplex)  I            0.00080      9.75   0.00104      1.18  -0.00020  [-0.00104,  0.00064]   0.00032      0.00     1.000\n  edge-based (multiplex)  cumulative   0.00129     12.25   0.00215      1.05  -0.00020  [-0.00104,  0.00064]  -0.00020      8.75     1.000\n  one layer, R₀ = 2       I            0.03454     10.50   0.00104     46.49  -0.04166  [-0.04250, -0.04082]  -0.02579      0.75     0.380\n  one layer, R₀ = 2       cumulative   0.08592     13.25   0.00215    100.91  -0.04166  [-0.04250, -0.04082]  -0.04166      8.75     0.003\n```\n:::\n:::\n\n\n\nThe one-layer model has the right R₀ and the right total degrees, but it is not the multiplex\nepidemic. It has one transmission rate for all edges, while the household edges transmit three\ntimes faster, and it matches stubs across layers.\n\n::: {.cell execution_count=1}\n\n::: {.cell-output .cell-output-display .cell-output-markdown execution_count=1}\nThe multiplex EBCM has D∞(I) = 0.0008 and ΔR∞ = -0.0002; the one-layer model has D∞(I) = 0.0345 and ΔR∞ = -0.0417.\n\n:::\n:::\n\n\n\n## Lean\n\n- `NEP.spectralRadius_fin_two`: the spectral radius of a 2 × 2 matrix with non-negative diagonal\n  and K₁₂K₂₁ ≥ 0.\n- `NEP.multiplex_r0_of_entries`: the two-layer spectral radius formula (the NGM is taken as\n  given; its derivation from the multiplex EB model is not formalised).\n- `NEP.multiplex_r0_eq_sum_iff_of_entries`: when the spectral radius equals the sum of the layer\n  R₀'s.\n\n## References\n\n::: {#refs}\n:::\n\n",
    "supporting": [
      "index_files/figure-pdf"
    ],
    "filters": [],
    "includes": {}
  }
}